#
# Autogenerated by Thrift Compiler (0.22.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec
from uuid import UUID

import sys
import tapsonic.common.ttypes

from thrift.transport import TTransport
all_structs = []


class buyContentsDataInfo(object):
    """
    Attributes:
     - u_seq
     - u_id
     - uuid
     - device_uuid
     - type
     - idx

    """
    thrift_spec = None


    def __init__(self, u_seq = None, u_id = None, uuid = None, device_uuid = None, type = None, idx = None,):
        self.u_seq = u_seq
        self.u_id = u_id
        self.uuid = uuid
        self.device_uuid = device_uuid
        self.type = type
        self.idx = idx

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.u_seq = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRING:
                    self.u_id = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.uuid = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRING:
                    self.device_uuid = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.STRING:
                    self.type = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.I32:
                    self.idx = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('buyContentsDataInfo')
        if self.u_seq is not None:
            oprot.writeFieldBegin('u_seq', TType.I32, 1)
            oprot.writeI32(self.u_seq)
            oprot.writeFieldEnd()
        if self.u_id is not None:
            oprot.writeFieldBegin('u_id', TType.STRING, 2)
            oprot.writeString(self.u_id.encode('utf-8') if sys.version_info[0] == 2 else self.u_id)
            oprot.writeFieldEnd()
        if self.uuid is not None:
            oprot.writeFieldBegin('uuid', TType.STRING, 3)
            oprot.writeString(self.uuid.encode('utf-8') if sys.version_info[0] == 2 else self.uuid)
            oprot.writeFieldEnd()
        if self.device_uuid is not None:
            oprot.writeFieldBegin('device_uuid', TType.STRING, 4)
            oprot.writeString(self.device_uuid.encode('utf-8') if sys.version_info[0] == 2 else self.device_uuid)
            oprot.writeFieldEnd()
        if self.type is not None:
            oprot.writeFieldBegin('type', TType.STRING, 5)
            oprot.writeString(self.type.encode('utf-8') if sys.version_info[0] == 2 else self.type)
            oprot.writeFieldEnd()
        if self.idx is not None:
            oprot.writeFieldBegin('idx', TType.I32, 6)
            oprot.writeI32(self.idx)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class buyContents(object):
    """
    Attributes:
     - call
     - data
     - sub_mode
     - common_data

    """
    thrift_spec = None


    def __init__(self, call = None, data = None, sub_mode = None, common_data = None,):
        self.call = call
        self.data = data
        self.sub_mode = sub_mode
        self.common_data = common_data

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.call = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.data = buyContentsDataInfo()
                    self.data.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.sub_mode = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRUCT:
                    self.common_data = tapsonic.common.ttypes.paramData()
                    self.common_data.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('buyContents')
        if self.call is not None:
            oprot.writeFieldBegin('call', TType.STRING, 1)
            oprot.writeString(self.call.encode('utf-8') if sys.version_info[0] == 2 else self.call)
            oprot.writeFieldEnd()
        if self.data is not None:
            oprot.writeFieldBegin('data', TType.STRUCT, 2)
            self.data.write(oprot)
            oprot.writeFieldEnd()
        if self.sub_mode is not None:
            oprot.writeFieldBegin('sub_mode', TType.STRING, 3)
            oprot.writeString(self.sub_mode.encode('utf-8') if sys.version_info[0] == 2 else self.sub_mode)
            oprot.writeFieldEnd()
        if self.common_data is not None:
            oprot.writeFieldBegin('common_data', TType.STRUCT, 4)
            self.common_data.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class buyContentsRetDataInfo(object):
    """
    Attributes:
     - u_cp
     - u_candy
     - user_skill
     - user_unit

    """
    thrift_spec = None


    def __init__(self, u_cp = None, u_candy = None, user_skill = None, user_unit = None,):
        self.u_cp = u_cp
        self.u_candy = u_candy
        self.user_skill = user_skill
        self.user_unit = user_unit

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.u_cp = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.DOUBLE:
                    self.u_candy = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRUCT:
                    self.user_skill = tapsonic.common.ttypes.userSkill()
                    self.user_skill.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRUCT:
                    self.user_unit = tapsonic.common.ttypes.userUnit()
                    self.user_unit.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('buyContentsRetDataInfo')
        if self.u_cp is not None:
            oprot.writeFieldBegin('u_cp', TType.I64, 1)
            oprot.writeI64(self.u_cp)
            oprot.writeFieldEnd()
        if self.u_candy is not None:
            oprot.writeFieldBegin('u_candy', TType.DOUBLE, 2)
            oprot.writeDouble(self.u_candy)
            oprot.writeFieldEnd()
        if self.user_skill is not None:
            oprot.writeFieldBegin('user_skill', TType.STRUCT, 3)
            self.user_skill.write(oprot)
            oprot.writeFieldEnd()
        if self.user_unit is not None:
            oprot.writeFieldBegin('user_unit', TType.STRUCT, 4)
            self.user_unit.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class buyContentsReturn(object):
    """
    Attributes:
     - error
     - server_time
     - mode
     - call
     - data
     - maintenance

    """
    thrift_spec = None


    def __init__(self, error = None, server_time = None, mode = None, call = None, data = None, maintenance = None,):
        self.error = error
        self.server_time = server_time
        self.mode = mode
        self.call = call
        self.data = data
        self.maintenance = maintenance

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.error = tapsonic.common.ttypes.errorRetCode()
                    self.error.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.server_time = tapsonic.common.ttypes.serverTimeRet()
                    self.server_time.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.mode = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRING:
                    self.call = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.STRUCT:
                    self.data = buyContentsRetDataInfo()
                    self.data.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.STRUCT:
                    self.maintenance = tapsonic.common.ttypes.maintenanceData()
                    self.maintenance.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('buyContentsReturn')
        if self.error is not None:
            oprot.writeFieldBegin('error', TType.STRUCT, 1)
            self.error.write(oprot)
            oprot.writeFieldEnd()
        if self.server_time is not None:
            oprot.writeFieldBegin('server_time', TType.STRUCT, 2)
            self.server_time.write(oprot)
            oprot.writeFieldEnd()
        if self.mode is not None:
            oprot.writeFieldBegin('mode', TType.STRING, 3)
            oprot.writeString(self.mode.encode('utf-8') if sys.version_info[0] == 2 else self.mode)
            oprot.writeFieldEnd()
        if self.call is not None:
            oprot.writeFieldBegin('call', TType.STRING, 4)
            oprot.writeString(self.call.encode('utf-8') if sys.version_info[0] == 2 else self.call)
            oprot.writeFieldEnd()
        if self.data is not None:
            oprot.writeFieldBegin('data', TType.STRUCT, 5)
            self.data.write(oprot)
            oprot.writeFieldEnd()
        if self.maintenance is not None:
            oprot.writeFieldBegin('maintenance', TType.STRUCT, 6)
            self.maintenance.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(buyContentsDataInfo)
buyContentsDataInfo.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'u_seq', None, None, ),  # 1
    (2, TType.STRING, 'u_id', 'UTF8', None, ),  # 2
    (3, TType.STRING, 'uuid', 'UTF8', None, ),  # 3
    (4, TType.STRING, 'device_uuid', 'UTF8', None, ),  # 4
    (5, TType.STRING, 'type', 'UTF8', None, ),  # 5
    (6, TType.I32, 'idx', None, None, ),  # 6
)
all_structs.append(buyContents)
buyContents.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'call', 'UTF8', None, ),  # 1
    (2, TType.STRUCT, 'data', [buyContentsDataInfo, None], None, ),  # 2
    (3, TType.STRING, 'sub_mode', 'UTF8', None, ),  # 3
    (4, TType.STRUCT, 'common_data', [tapsonic.common.ttypes.paramData, None], None, ),  # 4
)
all_structs.append(buyContentsRetDataInfo)
buyContentsRetDataInfo.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'u_cp', None, None, ),  # 1
    (2, TType.DOUBLE, 'u_candy', None, None, ),  # 2
    (3, TType.STRUCT, 'user_skill', [tapsonic.common.ttypes.userSkill, None], None, ),  # 3
    (4, TType.STRUCT, 'user_unit', [tapsonic.common.ttypes.userUnit, None], None, ),  # 4
)
all_structs.append(buyContentsReturn)
buyContentsReturn.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'error', [tapsonic.common.ttypes.errorRetCode, None], None, ),  # 1
    (2, TType.STRUCT, 'server_time', [tapsonic.common.ttypes.serverTimeRet, None], None, ),  # 2
    (3, TType.STRING, 'mode', 'UTF8', None, ),  # 3
    (4, TType.STRING, 'call', 'UTF8', None, ),  # 4
    (5, TType.STRUCT, 'data', [buyContentsRetDataInfo, None], None, ),  # 5
    (6, TType.STRUCT, 'maintenance', [tapsonic.common.ttypes.maintenanceData, None], None, ),  # 6
)
fix_spec(all_structs)
del all_structs
