from django.db import models

class ConsumeData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    s_ResourceName = models.TextField(null=True, blank=True)
    s_Title_KO = models.TextField(null=True, blank=True)
    s_Title_EN = models.TextField(null=True, blank=True)
    s_Title_JA = models.TextField(null=True, blank=True)
    s_Title_ZH_CHS = models.TextField(null=True, blank=True)
    s_Title_ZH_CHT = models.TextField(null=True, blank=True)
    s_Title_VI = models.TextField(null=True, blank=True)
    s_Title_ES = models.TextField(null=True, blank=True)
    s_Title_IT = models.TextField(null=True, blank=True)
    s_Title_ID = models.TextField(null=True, blank=True)
    s_Title_TH = models.TextField(null=True, blank=True)
    s_Title_PT = models.TextField(null=True, blank=True)
    s_Title_HI = models.TextField(null=True, blank=True)
    s_Limit = models.TextField(null=True, blank=True)
    i_Type = models.IntegerField(null=True, blank=True)
    s_ExtraValue = models.TextField(null=True, blank=True)
    i_Area = models.IntegerField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'ConsumeData {self.pk}'

class MusicData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    s_Title_KO = models.TextField(null=True, blank=True)
    s_Title_EN = models.TextField(null=True, blank=True)
    s_Title_JA = models.TextField(null=True, blank=True)
    s_Title_ZH_CHS = models.TextField(null=True, blank=True)
    s_Title_ZH_CHT = models.TextField(null=True, blank=True)
    s_Title_VI = models.TextField(null=True, blank=True)
    s_Title_ES = models.TextField(null=True, blank=True)
    s_Title_IT = models.TextField(null=True, blank=True)
    s_Title_ID = models.TextField(null=True, blank=True)
    s_Title_TH = models.TextField(null=True, blank=True)
    s_Title_PT = models.TextField(null=True, blank=True)
    s_Title_HI = models.TextField(null=True, blank=True)
    s_Description_1_KO = models.TextField(null=True, blank=True)
    s_Description_1_EN = models.TextField(null=True, blank=True)
    s_Description_1_JA = models.TextField(null=True, blank=True)
    s_Description_1_ZH_CHS = models.TextField(null=True, blank=True)
    s_Description_1_ZH_CHT = models.TextField(null=True, blank=True)
    s_Description_1_VI = models.TextField(null=True, blank=True)
    s_Description_1_ES = models.TextField(null=True, blank=True)
    s_Description_1_IT = models.TextField(null=True, blank=True)
    s_Description_1_ID = models.TextField(null=True, blank=True)
    s_Description_1_TH = models.TextField(null=True, blank=True)
    s_Description_1_PT = models.TextField(null=True, blank=True)
    s_Description_1_HI = models.TextField(null=True, blank=True)
    s_ResourceName = models.TextField(null=True, blank=True)
    s_MusicFileName = models.TextField(null=True, blank=True)
    i_MaxLevel = models.BigIntegerField(null=True, blank=True)
    d_LevelRate = models.FloatField(null=True, blank=True)
    d_LateCost = models.BigIntegerField(null=True, blank=True)
    d_Cost = models.FloatField(null=True, blank=True)
    d_CostIncreaseValue = models.FloatField(null=True, blank=True)
    d_CostValueConstant = models.BigIntegerField(null=True, blank=True)
    d_Amount = models.FloatField(null=True, blank=True)
    d_AmountIncreaseValue = models.FloatField(null=True, blank=True)
    d_AmountValueConstant = models.BigIntegerField(null=True, blank=True)
    d_BonusAmountIncreaseRate = models.BigIntegerField(null=True, blank=True)
    i_UnlockLevel = models.BigIntegerField(null=True, blank=True)
    d_UnlockCost = models.BigIntegerField(null=True, blank=True)
    i_RequirementFollowerId_1 = models.BigIntegerField(null=True, blank=True)
    i_RequirementFollowerId_2 = models.BigIntegerField(null=True, blank=True)
    i_RequirementMusicId_1 = models.BigIntegerField(null=True, blank=True)
    i_RequirementMusicId_2 = models.BigIntegerField(null=True, blank=True)
    i_RequirementMusicCount = models.BigIntegerField(null=True, blank=True)
    s_GoodsType = models.TextField(null=True, blank=True)
    i_SortOrder = models.BigIntegerField(null=True, blank=True)
    i_AcquisitionType = models.BigIntegerField(null=True, blank=True)
    i_AcquisitionId = models.BigIntegerField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)
    i_Area = models.IntegerField(null=True, blank=True)
    i_DownloadType_img = models.IntegerField(null=True, blank=True)
    i_DownloadType_file = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'MusicData {self.pk}'

class CostumeData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    s_Name_KO = models.TextField(null=True, blank=True)
    s_Name_EN = models.TextField(null=True, blank=True)
    s_Name_JA = models.TextField(null=True, blank=True)
    s_Name_ZH_CHS = models.TextField(null=True, blank=True)
    s_Name_ZH_CHT = models.TextField(null=True, blank=True)
    s_Name_VI = models.TextField(null=True, blank=True)
    s_Name_ES = models.TextField(null=True, blank=True)
    s_Name_IT = models.TextField(null=True, blank=True)
    s_Name_ID = models.TextField(null=True, blank=True)
    s_Name_TH = models.TextField(null=True, blank=True)
    s_Name_PT = models.TextField(null=True, blank=True)
    s_Name_HI = models.TextField(null=True, blank=True)
    s_Description_KO = models.TextField(null=True, blank=True)
    s_Description_EN = models.TextField(null=True, blank=True)
    s_Description_JA = models.TextField(null=True, blank=True)
    s_Description_ZH_CHS = models.TextField(null=True, blank=True)
    s_Description_ZH_CHT = models.TextField(null=True, blank=True)
    s_Description_VI = models.TextField(null=True, blank=True)
    s_Description_ES = models.TextField(null=True, blank=True)
    s_Description_IT = models.TextField(null=True, blank=True)
    s_Description_ID = models.TextField(null=True, blank=True)
    s_Description_TH = models.TextField(null=True, blank=True)
    s_Description_PT = models.TextField(null=True, blank=True)
    s_Description_HI = models.TextField(null=True, blank=True)
    s_ResourceName = models.TextField(null=True, blank=True)
    s_CostumeName = models.TextField(null=True, blank=True)
    i_MaxLevel = models.BigIntegerField(null=True, blank=True)
    s_GoodsType = models.TextField(null=True, blank=True)
    s_Cost = models.TextField(null=True, blank=True)
    f_CostIncreaseRate = models.FloatField(null=True, blank=True)
    s_Operation = models.TextField(null=True, blank=True)
    d_Amount = models.BigIntegerField(null=True, blank=True)
    f_AmountIncreaseRate = models.FloatField(null=True, blank=True)
    s_BonusOperation = models.TextField(null=True, blank=True)
    d_BonusAmount = models.BigIntegerField(null=True, blank=True)
    f_BonusAmountIncreaseRate = models.FloatField(null=True, blank=True)
    i_UnlockLevel = models.BigIntegerField(null=True, blank=True)
    i_RequirementFollowerId_1 = models.BigIntegerField(null=True, blank=True)
    i_RequirementFollowerId_2 = models.BigIntegerField(null=True, blank=True)
    i_RequirementPropId_1 = models.BigIntegerField(null=True, blank=True)
    i_RequirementPropId_2 = models.BigIntegerField(null=True, blank=True)
    i_RequirementPropCount = models.BigIntegerField(null=True, blank=True)
    i_SortOrder = models.BigIntegerField(null=True, blank=True)
    f_FanMultiply = models.FloatField(null=True, blank=True)
    i_AcquisitionType = models.BigIntegerField(null=True, blank=True)
    i_AcquisitionId = models.BigIntegerField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)
    i_Area = models.IntegerField(null=True, blank=True)
    i_DownloadType = models.IntegerField(null=True, blank=True)
    s_AltCostumeName = models.TextField(null=True, blank=True)
    s_AltCostumeStartTime = models.TextField(null=True, blank=True)
    s_AltCostumeEndTime = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'CostumeData {self.pk}'

class PropData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    s_Name_KO = models.TextField(null=True, blank=True)
    s_Name_EN = models.TextField(null=True, blank=True)
    s_Name_JA = models.TextField(null=True, blank=True)
    s_Name_ZH_CHS = models.TextField(null=True, blank=True)
    s_Name_ZH_CHT = models.TextField(null=True, blank=True)
    s_Name_VI = models.TextField(null=True, blank=True)
    s_Name_ES = models.TextField(null=True, blank=True)
    s_Name_IT = models.TextField(null=True, blank=True)
    s_Name_ID = models.TextField(null=True, blank=True)
    s_Name_TH = models.TextField(null=True, blank=True)
    s_Name_PT = models.TextField(null=True, blank=True)
    s_Name_HI = models.TextField(null=True, blank=True)
    s_Description_KO = models.TextField(null=True, blank=True)
    s_Description_EN = models.TextField(null=True, blank=True)
    s_Description_JA = models.TextField(null=True, blank=True)
    s_Description_ZH_CHS = models.TextField(null=True, blank=True)
    s_Description_ZH_CHT = models.TextField(null=True, blank=True)
    s_Description_VI = models.TextField(null=True, blank=True)
    s_Description_ES = models.TextField(null=True, blank=True)
    s_Description_IT = models.TextField(null=True, blank=True)
    s_Description_ID = models.TextField(null=True, blank=True)
    s_Description_TH = models.TextField(null=True, blank=True)
    s_Description_PT = models.TextField(null=True, blank=True)
    s_Description_HI = models.TextField(null=True, blank=True)
    s_ResourceName = models.TextField(null=True, blank=True)
    i_RequirementPropId = models.BigIntegerField(null=True, blank=True)
    i_Area = models.BigIntegerField(null=True, blank=True)
    b_IsActive = models.BigIntegerField(null=True, blank=True)
    i_MaxLevel = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'PropData {self.pk}'

class FollowerData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    s_Name_KO = models.TextField(null=True, blank=True)
    s_Name_EN = models.TextField(null=True, blank=True)
    s_Name_JA = models.TextField(null=True, blank=True)
    s_Name_ZH_CHS = models.TextField(null=True, blank=True)
    s_Name_ZH_CHT = models.TextField(null=True, blank=True)
    s_Name_VI = models.TextField(null=True, blank=True)
    s_Name_ES = models.TextField(null=True, blank=True)
    s_Name_IT = models.TextField(null=True, blank=True)
    s_Name_ID = models.TextField(null=True, blank=True)
    s_Name_TH = models.TextField(null=True, blank=True)
    s_Name_PT = models.TextField(null=True, blank=True)
    s_Name_HI = models.TextField(null=True, blank=True)
    s_Description_KO = models.TextField(null=True, blank=True)
    s_Description_EN = models.TextField(null=True, blank=True)
    s_Description_JA = models.TextField(null=True, blank=True)
    s_Description_ZH_CHS = models.TextField(null=True, blank=True)
    s_Description_ZH_CHT = models.TextField(null=True, blank=True)
    s_Description_VI = models.TextField(null=True, blank=True)
    s_Description_ES = models.TextField(null=True, blank=True)
    s_Description_IT = models.TextField(null=True, blank=True)
    s_Description_ID = models.TextField(null=True, blank=True)
    s_Description_TH = models.TextField(null=True, blank=True)
    s_Description_PT = models.TextField(null=True, blank=True)
    s_Description_HI = models.TextField(null=True, blank=True)
    s_ResourceName = models.TextField(null=True, blank=True)
    i_MaxLevel = models.BigIntegerField(null=True, blank=True)
    d_LevelRate = models.FloatField(null=True, blank=True)
    d_LateCost = models.BigIntegerField(null=True, blank=True)
    d_Cost = models.FloatField(null=True, blank=True)
    d_CostIncreaseValue = models.FloatField(null=True, blank=True)
    d_CostValueConstant = models.BigIntegerField(null=True, blank=True)
    d_Amount = models.FloatField(null=True, blank=True)
    d_AmountIncreaseValue = models.FloatField(null=True, blank=True)
    d_AmountValueConstant = models.BigIntegerField(null=True, blank=True)
    d_BonusAmountIncreaseRate = models.BigIntegerField(null=True, blank=True)
    i_UnlockLevel = models.BigIntegerField(null=True, blank=True)
    d_UnlockCost = models.BigIntegerField(null=True, blank=True)
    i_RequirementFollowerId_1 = models.BigIntegerField(null=True, blank=True)
    i_RequirementFollowerId_2 = models.BigIntegerField(null=True, blank=True)
    i_RequirementPropId_1 = models.BigIntegerField(null=True, blank=True)
    i_RequirementPropId_2 = models.BigIntegerField(null=True, blank=True)
    i_RequirementPropCount = models.BigIntegerField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)
    i_Area = models.IntegerField(null=True, blank=True)
    i_DownloadType = models.IntegerField(null=True, blank=True)
    i_ProfileID = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'FollowerData {self.pk}'

class BuffData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    s_ResourceName = models.TextField(null=True, blank=True)
    s_Title_KO = models.TextField(null=True, blank=True)
    s_Title_EN = models.TextField(null=True, blank=True)
    s_Title_JA = models.TextField(null=True, blank=True)
    s_Title_ZH_CHS = models.TextField(null=True, blank=True)
    s_Title_ZH_CHT = models.TextField(null=True, blank=True)
    s_Title_VI = models.TextField(null=True, blank=True)
    s_Title_ES = models.TextField(null=True, blank=True)
    s_Title_IT = models.TextField(null=True, blank=True)
    s_Title_ID = models.TextField(null=True, blank=True)
    s_Title_TH = models.TextField(null=True, blank=True)
    s_Title_PT = models.TextField(null=True, blank=True)
    s_Title_HI = models.TextField(null=True, blank=True)
    s_Buff_Desc_KO = models.TextField(null=True, blank=True)
    s_Buff_Desc_EN = models.TextField(null=True, blank=True)
    s_Buff_Desc_JA = models.TextField(null=True, blank=True)
    s_Buff_Desc_ZH_CHS = models.TextField(null=True, blank=True)
    s_Buff_Desc_ZH_CHT = models.TextField(null=True, blank=True)
    s_Buff_Desc_VI = models.TextField(null=True, blank=True)
    s_Buff_Desc_ES = models.TextField(null=True, blank=True)
    s_Buff_Desc_IT = models.TextField(null=True, blank=True)
    s_Buff_Desc_ID = models.TextField(null=True, blank=True)
    s_Buff_Desc_TH = models.TextField(null=True, blank=True)
    s_Buff_Desc_PT = models.TextField(null=True, blank=True)
    s_Buff_Desc_HI = models.TextField(null=True, blank=True)
    i_Type = models.IntegerField(null=True, blank=True)
    i_Retention_Time = models.BigIntegerField(null=True, blank=True)

    def __str__(self):
        return f'BuffData {self.pk}'

class UnitData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    s_Name_KO = models.TextField(null=True, blank=True)
    s_Name_EN = models.TextField(null=True, blank=True)
    s_Name_JA = models.TextField(null=True, blank=True)
    s_Name_ZH_CHS = models.TextField(null=True, blank=True)
    s_Name_ZH_CHT = models.TextField(null=True, blank=True)
    s_Name_VI = models.TextField(null=True, blank=True)
    s_Name_ES = models.TextField(null=True, blank=True)
    s_Name_IT = models.TextField(null=True, blank=True)
    s_Name_ID = models.TextField(null=True, blank=True)
    s_Name_TH = models.TextField(null=True, blank=True)
    s_Name_PT = models.TextField(null=True, blank=True)
    s_Name_HI = models.TextField(null=True, blank=True)
    s_Description_KO = models.TextField(null=True, blank=True)
    s_Description_EN = models.TextField(null=True, blank=True)
    s_Description_JA = models.TextField(null=True, blank=True)
    s_Description_ZH_CHS = models.TextField(null=True, blank=True)
    s_Description_ZH_CHT = models.TextField(null=True, blank=True)
    s_Description_VI = models.TextField(null=True, blank=True)
    s_Description_ES = models.TextField(null=True, blank=True)
    s_Description_IT = models.TextField(null=True, blank=True)
    s_Description_ID = models.TextField(null=True, blank=True)
    s_Description_TH = models.TextField(null=True, blank=True)
    s_Description_PT = models.TextField(null=True, blank=True)
    s_Description_HI = models.TextField(null=True, blank=True)
    s_ResourceName = models.TextField(null=True, blank=True)
    i_MaxLevel = models.BigIntegerField(null=True, blank=True)
    s_GoodsType = models.TextField(null=True, blank=True)
    i_Cost = models.FloatField(null=True, blank=True)
    f_CostIncreaseValue = models.FloatField(null=True, blank=True)
    f_Value = models.FloatField(null=True, blank=True)
    f_IncreaseValue = models.FloatField(null=True, blank=True)
    i_UnlockLevel = models.BigIntegerField(null=True, blank=True)
    i_UnlockCost = models.BigIntegerField(null=True, blank=True)
    i_RequirementUnitId_1 = models.BigIntegerField(null=True, blank=True)
    i_RequirementUnitId_2 = models.BigIntegerField(null=True, blank=True)
    i_RequirementFollowerId_1 = models.BigIntegerField(null=True, blank=True)
    i_RequirementFollowerId_2 = models.BigIntegerField(null=True, blank=True)
    i_RequirementPropId_1 = models.BigIntegerField(null=True, blank=True)
    i_RequirementPropId_2 = models.BigIntegerField(null=True, blank=True)
    i_RequirementPropCount = models.BigIntegerField(null=True, blank=True)
    i_Area = models.IntegerField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'UnitData {self.pk}'

class SkillData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    i_Area = models.IntegerField(null=True, blank=True)
    s_Name_KO = models.TextField(null=True, blank=True)
    s_Name_EN = models.TextField(null=True, blank=True)
    s_Name_JA = models.TextField(null=True, blank=True)
    s_Name_ZH_CHS = models.TextField(null=True, blank=True)
    s_Name_ZH_CHT = models.TextField(null=True, blank=True)
    s_Name_VI = models.TextField(null=True, blank=True)
    s_Name_ES = models.TextField(null=True, blank=True)
    s_Name_IT = models.TextField(null=True, blank=True)
    s_Name_ID = models.TextField(null=True, blank=True)
    s_Name_TH = models.TextField(null=True, blank=True)
    s_Name_PT = models.TextField(null=True, blank=True)
    s_Name_HI = models.TextField(null=True, blank=True)
    s_Description_KO = models.TextField(null=True, blank=True)
    s_Description_EN = models.TextField(null=True, blank=True)
    s_Description_JA = models.TextField(null=True, blank=True)
    s_Description_ZH_CHS = models.TextField(null=True, blank=True)
    s_Description_ZH_CHT = models.TextField(null=True, blank=True)
    s_Description_VI = models.TextField(null=True, blank=True)
    s_Description_ES = models.TextField(null=True, blank=True)
    s_Description_IT = models.TextField(null=True, blank=True)
    s_Description_ID = models.TextField(null=True, blank=True)
    s_Description_TH = models.TextField(null=True, blank=True)
    s_Description_PT = models.TextField(null=True, blank=True)
    s_Description_HI = models.TextField(null=True, blank=True)
    s_ResourceName = models.TextField(null=True, blank=True)
    i_MaxLevel = models.BigIntegerField(null=True, blank=True)
    s_GoodsType = models.TextField(null=True, blank=True)
    i_Cost = models.FloatField(null=True, blank=True)
    f_CostIncreaseValue = models.FloatField(null=True, blank=True)
    f_SkillValue = models.FloatField(null=True, blank=True)
    f_SkillIncreaseValue = models.FloatField(null=True, blank=True)
    f_SkillTime = models.FloatField(null=True, blank=True)
    f_SkillTimeIncreaseValue = models.FloatField(null=True, blank=True)
    f_Cooltime = models.FloatField(null=True, blank=True)
    i_UnlockLevel = models.BigIntegerField(null=True, blank=True)
    i_UnlockCost = models.BigIntegerField(null=True, blank=True)
    i_RequirementSkillId_1 = models.BigIntegerField(null=True, blank=True)
    i_RequirementSkillId_2 = models.BigIntegerField(null=True, blank=True)
    i_RequirementFollowerId_1 = models.BigIntegerField(null=True, blank=True)
    i_RequirementFollowerId_2 = models.BigIntegerField(null=True, blank=True)
    i_RequirementPropId_1 = models.BigIntegerField(null=True, blank=True)
    i_RequirementPropId_2 = models.BigIntegerField(null=True, blank=True)
    i_RequirementPropCount = models.BigIntegerField(null=True, blank=True)

    def __str__(self):
        return f'SkillData {self.pk}'

class AchievementData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    s_Title_KO = models.TextField(null=True, blank=True)
    s_Title_EN = models.TextField(null=True, blank=True)
    s_Title_JA = models.TextField(null=True, blank=True)
    s_Title_ZH_CHS = models.TextField(null=True, blank=True)
    s_Title_ZH_CHT = models.TextField(null=True, blank=True)
    s_Title_VI = models.TextField(null=True, blank=True)
    s_Title_ES = models.TextField(null=True, blank=True)
    s_Title_IT = models.TextField(null=True, blank=True)
    s_Title_ID = models.TextField(null=True, blank=True)
    s_Title_TH = models.TextField(null=True, blank=True)
    s_Title_PT = models.TextField(null=True, blank=True)
    s_Title_HI = models.TextField(null=True, blank=True)
    s_Description_KO = models.TextField(null=True, blank=True)
    s_Description_EN = models.TextField(null=True, blank=True)
    s_Description_JA = models.TextField(null=True, blank=True)
    s_Description_ZH_CHS = models.TextField(null=True, blank=True)
    s_Description_ZH_CHT = models.TextField(null=True, blank=True)
    s_Description_VI = models.TextField(null=True, blank=True)
    s_Description_ES = models.TextField(null=True, blank=True)
    s_Description_IT = models.TextField(null=True, blank=True)
    s_Description_ID = models.TextField(null=True, blank=True)
    s_Description_TH = models.TextField(null=True, blank=True)
    s_Description_PT = models.TextField(null=True, blank=True)
    s_Description_HI = models.TextField(null=True, blank=True)
    s_ResourceName = models.TextField(null=True, blank=True)
    s_AchievementConditionType = models.TextField(null=True, blank=True)
    s_RewardType = models.TextField(null=True, blank=True)
    s_RewardDescription_KO = models.TextField(null=True, blank=True)
    s_RewardDescription_EN = models.TextField(null=True, blank=True)
    s_RewardDescription_JA = models.TextField(null=True, blank=True)
    s_RewardDescription_ZH_CHS = models.TextField(null=True, blank=True)
    s_RewardDescription_ZH_CHT = models.TextField(null=True, blank=True)
    s_RewardDescription_VI = models.TextField(null=True, blank=True)
    s_RewardDescription_ES = models.TextField(null=True, blank=True)
    s_RewardDescription_IT = models.TextField(null=True, blank=True)
    s_RewardDescription_ID = models.TextField(null=True, blank=True)
    s_RewardDescription_TH = models.TextField(null=True, blank=True)
    s_RewardDescription_PT = models.TextField(null=True, blank=True)
    s_RewardDescription_HI = models.TextField(null=True, blank=True)
    i_Reward_1 = models.BigIntegerField(null=True, blank=True)
    i_Reward_2 = models.BigIntegerField(null=True, blank=True)
    i_Reward_3 = models.BigIntegerField(null=True, blank=True)
    i_Reward_4 = models.BigIntegerField(null=True, blank=True)
    i_Reward_5 = models.BigIntegerField(null=True, blank=True)
    i_Reward_6 = models.BigIntegerField(null=True, blank=True)
    i_Reward_7 = models.BigIntegerField(null=True, blank=True)
    i_Reward_8 = models.BigIntegerField(null=True, blank=True)
    i_Reward_9 = models.BigIntegerField(null=True, blank=True)
    i_Reward_10 = models.BigIntegerField(null=True, blank=True)
    i_Area = models.IntegerField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)
    i_Reward_11 = models.BigIntegerField(null=True, blank=True)
    i_Reward_12 = models.BigIntegerField(null=True, blank=True)
    i_MaxLevel = models.IntegerField(null=True, blank=True)
    s_Condition_1 = models.TextField(null=True, blank=True)
    s_Condition_2 = models.TextField(null=True, blank=True)
    s_Condition_3 = models.TextField(null=True, blank=True)
    s_Condition_4 = models.TextField(null=True, blank=True)
    s_Condition_5 = models.TextField(null=True, blank=True)
    s_Condition_6 = models.TextField(null=True, blank=True)
    s_Condition_7 = models.TextField(null=True, blank=True)
    s_Condition_8 = models.TextField(null=True, blank=True)
    s_Condition_9 = models.TextField(null=True, blank=True)
    s_Condition_10 = models.TextField(null=True, blank=True)
    s_Condition_11 = models.TextField(null=True, blank=True)
    s_Condition_12 = models.TextField(null=True, blank=True)
    s_Condition_13 = models.TextField(null=True, blank=True)
    s_Condition_14 = models.TextField(null=True, blank=True)
    s_Condition_15 = models.TextField(null=True, blank=True)
    s_Condition_16 = models.TextField(null=True, blank=True)
    s_Condition_17 = models.TextField(null=True, blank=True)
    s_Condition_18 = models.TextField(null=True, blank=True)
    s_Condition_19 = models.TextField(null=True, blank=True)
    s_Condition_20 = models.TextField(null=True, blank=True)
    i_Reward_13 = models.BigIntegerField(null=True, blank=True)
    i_Reward_14 = models.BigIntegerField(null=True, blank=True)
    i_Reward_15 = models.BigIntegerField(null=True, blank=True)
    i_Reward_16 = models.BigIntegerField(null=True, blank=True)
    i_Reward_17 = models.BigIntegerField(null=True, blank=True)
    i_Reward_18 = models.BigIntegerField(null=True, blank=True)
    i_Reward_19 = models.BigIntegerField(null=True, blank=True)
    i_Reward_20 = models.BigIntegerField(null=True, blank=True)

    def __str__(self):
        return f'AchievementData {self.pk}'

class DailyMissionData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    s_Title_KO = models.TextField(null=True, blank=True)
    s_Title_EN = models.TextField(null=True, blank=True)
    s_Title_JA = models.TextField(null=True, blank=True)
    s_Title_ZH_CHS = models.TextField(null=True, blank=True)
    s_Title_ZH_CHT = models.TextField(null=True, blank=True)
    s_Title_VI = models.TextField(null=True, blank=True)
    s_Title_ES = models.TextField(null=True, blank=True)
    s_Title_IT = models.TextField(null=True, blank=True)
    s_Title_ID = models.TextField(null=True, blank=True)
    s_Title_TH = models.TextField(null=True, blank=True)
    s_Title_PT = models.TextField(null=True, blank=True)
    s_Title_HI = models.TextField(null=True, blank=True)
    s_Description_KO = models.TextField(null=True, blank=True)
    s_Description_EN = models.TextField(null=True, blank=True)
    s_Description_JA = models.TextField(null=True, blank=True)
    s_Description_ZH_CHS = models.TextField(null=True, blank=True)
    s_Description_ZH_CHT = models.TextField(null=True, blank=True)
    s_Description_VI = models.TextField(null=True, blank=True)
    s_Description_ES = models.TextField(null=True, blank=True)
    s_Description_IT = models.TextField(null=True, blank=True)
    s_Description_ID = models.TextField(null=True, blank=True)
    s_Description_TH = models.TextField(null=True, blank=True)
    s_Description_PT = models.TextField(null=True, blank=True)
    s_Description_HI = models.TextField(null=True, blank=True)
    s_ResourceName = models.TextField(null=True, blank=True)
    s_DailyMissionConditionType = models.TextField(null=True, blank=True)
    d_Condition_1 = models.FloatField(null=True, blank=True)
    s_RewardType = models.TextField(null=True, blank=True)
    s_RewardDescription_KO = models.TextField(null=True, blank=True)
    s_RewardDescription_EN = models.TextField(null=True, blank=True)
    s_RewardDescription_JA = models.TextField(null=True, blank=True)
    s_RewardDescription_ZH_CHS = models.TextField(null=True, blank=True)
    s_RewardDescription_ZH_CHT = models.TextField(null=True, blank=True)
    s_RewardDescription_VI = models.TextField(null=True, blank=True)
    s_RewardDescription_ES = models.TextField(null=True, blank=True)
    s_RewardDescription_IT = models.TextField(null=True, blank=True)
    s_RewardDescription_ID = models.TextField(null=True, blank=True)
    s_RewardDescription_TH = models.TextField(null=True, blank=True)
    s_RewardDescription_PT = models.TextField(null=True, blank=True)
    s_RewardDescription_HI = models.TextField(null=True, blank=True)
    i_Reward_1 = models.IntegerField(null=True, blank=True)
    i_Area = models.IntegerField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'DailyMissionData {self.pk}'

class MusicLevelData(models.Model):
    i_Level = models.IntegerField(null=True, blank=True)
    f_EncoreBonusAppearRate = models.FloatField(null=True, blank=True)
    i_EncoreBonusAppearPercent = models.BigIntegerField(null=True, blank=True)
    f_EncoreBonusAppearCooltime_Sec = models.FloatField(null=True, blank=True)
    f_EncoreBonusAppearCooltime_Hour = models.FloatField(null=True, blank=True)
    i_EncoreBonusGiftAmount = models.IntegerField(null=True, blank=True)
    i_EncoreFollowerProfileExp = models.IntegerField(null=True, blank=True)
    i_ChThirdCoolTime = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'MusicLevelData {self.pk}'

class ShopData(models.Model):
    i_id = models.BigIntegerField(null=True, blank=True)
    s_ProductID_ios = models.TextField(null=True, blank=True)
    s_ProductID_aos = models.TextField(null=True, blank=True)
    i_ShopCategory = models.BigIntegerField(null=True, blank=True)
    i_ProductType = models.BigIntegerField(null=True, blank=True)
    s_ResourceName = models.TextField(null=True, blank=True)
    s_Title_KO = models.TextField(null=True, blank=True)
    s_Title_EN = models.TextField(null=True, blank=True)
    s_Title_JA = models.TextField(null=True, blank=True)
    s_Title_ZH_CHS = models.TextField(null=True, blank=True)
    s_Title_ZH_CHT = models.TextField(null=True, blank=True)
    s_Title_VI = models.TextField(null=True, blank=True)
    s_Title_ES = models.TextField(null=True, blank=True)
    s_Title_IT = models.TextField(null=True, blank=True)
    s_Title_ID = models.TextField(null=True, blank=True)
    s_Title_TH = models.TextField(null=True, blank=True)
    s_Title_PT = models.TextField(null=True, blank=True)
    s_Title_HI = models.TextField(null=True, blank=True)
    s_Description_KO = models.TextField(null=True, blank=True)
    s_Description_EN = models.TextField(null=True, blank=True)
    s_Description_JA = models.TextField(null=True, blank=True)
    s_Description_ZH_CHS = models.TextField(null=True, blank=True)
    s_Description_ZH_CHT = models.TextField(null=True, blank=True)
    s_Description_VI = models.TextField(null=True, blank=True)
    s_Description_ES = models.TextField(null=True, blank=True)
    s_Description_IT = models.TextField(null=True, blank=True)
    s_Description_ID = models.TextField(null=True, blank=True)
    s_Description_TH = models.TextField(null=True, blank=True)
    s_Description_PT = models.TextField(null=True, blank=True)
    s_Description_HI = models.TextField(null=True, blank=True)
    i_RewardGroup = models.BigIntegerField(null=True, blank=True)
    i_Tag = models.BigIntegerField(null=True, blank=True)
    i_SellType = models.BigIntegerField(null=True, blank=True)
    i_SellValue = models.BigIntegerField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)
    i_Condition = models.BigIntegerField(null=True, blank=True)
    i_ConditionValue = models.BigIntegerField(null=True, blank=True)
    s_StorePrice_AOS = models.TextField(null=True, blank=True)
    s_StorePrice_IOS = models.TextField(null=True, blank=True)
    i_SortIndex = models.IntegerField(null=True, blank=True)
    s_AreaList = models.TextField(null=True, blank=True)
    s_AltResourceName = models.TextField(null=True, blank=True)
    s_AltDescription_KO = models.TextField(null=True, blank=True)
    s_AltDescription_EN = models.TextField(null=True, blank=True)
    s_AltDescription_JA = models.TextField(null=True, blank=True)
    s_AltDescription_ZH_CHS = models.TextField(null=True, blank=True)
    s_AltDescription_ZH_CHT = models.TextField(null=True, blank=True)
    s_AltDescription_VI = models.TextField(null=True, blank=True)
    s_AltDescription_ES = models.TextField(null=True, blank=True)
    s_AltDescription_IT = models.TextField(null=True, blank=True)
    s_AltDescription_ID = models.TextField(null=True, blank=True)
    s_AltDescription_TH = models.TextField(null=True, blank=True)
    s_AltDescription_PT = models.TextField(null=True, blank=True)
    s_AltDescription_HI = models.TextField(null=True, blank=True)
    s_Kor_StorePrice_AOS = models.TextField(null=True, blank=True)
    s_Kor_StorePrice_IOS = models.TextField(null=True, blank=True)
    b_IsLimitTime = models.IntegerField(null=True, blank=True)
    s_UIStartTime = models.TextField(null=True, blank=True)
    s_StartTime = models.TextField(null=True, blank=True)
    s_EndTime = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'ShopData {self.pk}'

class RewardGroupData(models.Model):
    i_id = models.BigIntegerField(null=True, blank=True)
    i_Group = models.BigIntegerField(null=True, blank=True)
    i_RewardType = models.BigIntegerField(null=True, blank=True)
    i_RewardID = models.BigIntegerField(null=True, blank=True)
    l_RewardQuantity = models.BigIntegerField(null=True, blank=True)
    i_BuyFirstQuantity = models.BigIntegerField(null=True, blank=True)

    def __str__(self):
        return f'RewardGroupData {self.pk}'

class FanData(models.Model):
    i_Area = models.BigIntegerField(null=True, blank=True)
    i_Grade = models.BigIntegerField(null=True, blank=True)
    i_FanCount = models.BigIntegerField(null=True, blank=True)
    i_BonusRate = models.BigIntegerField(null=True, blank=True)
    i_BonusRateUI = models.BigIntegerField(null=True, blank=True)

    def __str__(self):
        return f'FanData {self.pk}'

class SystemNotificationData(models.Model):
    i_Id = models.BigIntegerField(null=True, blank=True)
    s_DescriptionType = models.TextField(null=True, blank=True)
    i_Type = models.TextField(null=True, blank=True)
    s_Factor = models.TextField(null=True, blank=True)
    s_Description_KO = models.TextField(null=True, blank=True)
    s_Description_EN = models.TextField(null=True, blank=True)
    s_Description_JA = models.TextField(null=True, blank=True)
    s_Description_ZH_CHS = models.TextField(null=True, blank=True)
    s_Description_ZH_CHT = models.TextField(null=True, blank=True)
    s_Description_VI = models.TextField(null=True, blank=True)
    s_Description_ES = models.TextField(null=True, blank=True)
    s_Description_IT = models.TextField(null=True, blank=True)
    s_Description_ID = models.TextField(null=True, blank=True)
    s_Description_TH = models.TextField(null=True, blank=True)
    s_Description_PT = models.TextField(null=True, blank=True)
    s_Description_HI = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'SystemNotificationData {self.pk}'

class SystemStringData(models.Model):
    i_StringID = models.BigIntegerField(null=True, blank=True)
    s_Category = models.TextField(null=True, blank=True)
    s_UIType = models.TextField(null=True, blank=True)
    s_Key = models.TextField(null=True, blank=True)
    s_KO = models.TextField(null=True, blank=True)
    s_EN = models.TextField(null=True, blank=True)
    s_JA = models.TextField(null=True, blank=True)
    s_ZH_CHS = models.TextField(null=True, blank=True)
    s_ZH_CHT = models.TextField(null=True, blank=True)
    s_ID = models.TextField(null=True, blank=True)
    s_PT = models.TextField(null=True, blank=True)
    s_ES = models.TextField(null=True, blank=True)
    s_RU = models.TextField(null=True, blank=True)
    s_DE = models.TextField(null=True, blank=True)
    s_AR_XA = models.TextField(null=True, blank=True)
    s_VI = models.TextField(null=True, blank=True)
    s_IT = models.TextField(null=True, blank=True)
    s_TH = models.TextField(null=True, blank=True)
    s_HI = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'SystemStringData {self.pk}'

class SubscribeList(models.Model):
    i_id = models.BigIntegerField(null=True, blank=True)
    i_Area = models.IntegerField(null=True, blank=True)
    s_Type = models.TextField(null=True, blank=True)
    i_TimeLimit = models.IntegerField(null=True, blank=True)
    i_StartYear = models.IntegerField(null=True, blank=True)
    i_RepeatMonth = models.IntegerField(null=True, blank=True)
    i_MonthGroupIndex = models.IntegerField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'SubscribeList {self.pk}'

class SubscribePassReward(models.Model):
    i_id = models.BigIntegerField(null=True, blank=True)
    i_Group = models.BigIntegerField(null=True, blank=True)
    i_Step = models.IntegerField(null=True, blank=True)
    i_Goal = models.BigIntegerField(null=True, blank=True)
    i_FreeRewardGroup = models.BigIntegerField(null=True, blank=True)
    i_PaidRewardGroup = models.BigIntegerField(null=True, blank=True)

    def __str__(self):
        return f'SubscribePassReward {self.pk}'

class SubscribePass(models.Model):
    i_id = models.BigIntegerField(null=True, blank=True)
    i_SubscribeID = models.BigIntegerField(null=True, blank=True)
    s_AcquireList = models.TextField(null=True, blank=True)
    i_PointPrice = models.IntegerField(null=True, blank=True)
    i_PaidPoint = models.BigIntegerField(null=True, blank=True)
    i_ActiveBuffID = models.BigIntegerField(null=True, blank=True)
    i_HiddenStep = models.BigIntegerField(null=True, blank=True)
    i_ADPoint = models.BigIntegerField(null=True, blank=True)
    i_ADCoolTime = models.BigIntegerField(null=True, blank=True)
    i_TicketCollectionId = models.BigIntegerField(null=True, blank=True)

    def __str__(self):
        return f'SubscribePass {self.pk}'

class GuitarData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    i_Area = models.IntegerField(null=True, blank=True)
    s_Title_KO = models.TextField(null=True, blank=True)
    s_Title_EN = models.TextField(null=True, blank=True)
    s_Title_JA = models.TextField(null=True, blank=True)
    s_Title_ZH_CHS = models.TextField(null=True, blank=True)
    s_Title_ZH_CHT = models.TextField(null=True, blank=True)
    s_Title_VI = models.TextField(null=True, blank=True)
    s_Title_ES = models.TextField(null=True, blank=True)
    s_Title_IT = models.TextField(null=True, blank=True)
    s_Title_ID = models.TextField(null=True, blank=True)
    s_Title_TH = models.TextField(null=True, blank=True)
    s_Title_PT = models.TextField(null=True, blank=True)
    s_Title_HI = models.TextField(null=True, blank=True)
    s_Description_KO = models.TextField(null=True, blank=True)
    s_Description_EN = models.TextField(null=True, blank=True)
    s_Description_JA = models.TextField(null=True, blank=True)
    s_Description_ZH_CHS = models.TextField(null=True, blank=True)
    s_Description_ZH_CHT = models.TextField(null=True, blank=True)
    s_Description_VI = models.TextField(null=True, blank=True)
    s_Description_ES = models.TextField(null=True, blank=True)
    s_Description_IT = models.TextField(null=True, blank=True)
    s_Description_ID = models.TextField(null=True, blank=True)
    s_Description_TH = models.TextField(null=True, blank=True)
    s_Description_PT = models.TextField(null=True, blank=True)
    s_Description_HI = models.TextField(null=True, blank=True)
    s_ResourceName = models.TextField(null=True, blank=True)
    s_GuitarName = models.TextField(null=True, blank=True)
    i_GuitarType = models.IntegerField(null=True, blank=True)
    s_GoodsType = models.TextField(null=True, blank=True)
    s_Cost = models.TextField(null=True, blank=True)
    i_RequirementCharacterLevel = models.BigIntegerField(null=True, blank=True)
    d_IncrementValue = models.FloatField(null=True, blank=True)
    i_AcquisitionType = models.BigIntegerField(null=True, blank=True)
    i_AcquisitionId = models.BigIntegerField(null=True, blank=True)
    i_SortOrder = models.BigIntegerField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)
    i_DownloadType = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'GuitarData {self.pk}'

class SubscribePassRewardInformation(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    s_ResourceName = models.TextField(null=True, blank=True)
    s_Description_KO = models.TextField(null=True, blank=True)
    s_Description_EN = models.TextField(null=True, blank=True)
    s_Description_JA = models.TextField(null=True, blank=True)
    s_Description_ZH_CHS = models.TextField(null=True, blank=True)
    s_Description_ZH_CHT = models.TextField(null=True, blank=True)
    s_Description_VI = models.TextField(null=True, blank=True)
    s_Description_ES = models.TextField(null=True, blank=True)
    s_Description_IT = models.TextField(null=True, blank=True)
    s_Description_ID = models.TextField(null=True, blank=True)
    s_Description_TH = models.TextField(null=True, blank=True)
    s_Description_PT = models.TextField(null=True, blank=True)
    s_Description_HI = models.TextField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'SubscribePassRewardInformation {self.pk}'

class TicketCollectionData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    s_TicketType = models.TextField(null=True, blank=True)
    s_Title_KO = models.TextField(null=True, blank=True)
    s_Title_EN = models.TextField(null=True, blank=True)
    s_Title_JA = models.TextField(null=True, blank=True)
    s_Title_ZH_CHS = models.TextField(null=True, blank=True)
    s_Title_ZH_CHT = models.TextField(null=True, blank=True)
    s_Title_VI = models.TextField(null=True, blank=True)
    s_Title_ES = models.TextField(null=True, blank=True)
    s_Title_IT = models.TextField(null=True, blank=True)
    s_Title_ID = models.TextField(null=True, blank=True)
    s_Title_TH = models.TextField(null=True, blank=True)
    s_Title_PT = models.TextField(null=True, blank=True)
    s_Title_HI = models.TextField(null=True, blank=True)
    s_Description_KO = models.TextField(null=True, blank=True)
    s_Description_EN = models.TextField(null=True, blank=True)
    s_Description_JA = models.TextField(null=True, blank=True)
    s_Description_ZH_CHS = models.TextField(null=True, blank=True)
    s_Description_ZH_CHT = models.TextField(null=True, blank=True)
    s_Description_VI = models.TextField(null=True, blank=True)
    s_Description_ES = models.TextField(null=True, blank=True)
    s_Description_IT = models.TextField(null=True, blank=True)
    s_Description_ID = models.TextField(null=True, blank=True)
    s_Description_TH = models.TextField(null=True, blank=True)
    s_Description_PT = models.TextField(null=True, blank=True)
    s_Description_HI = models.TextField(null=True, blank=True)
    s_ResourceName = models.TextField(null=True, blank=True)
    s_ResourceName_Big = models.TextField(null=True, blank=True)
    i_Season = models.IntegerField(null=True, blank=True)
    s_PassUIBundleName = models.TextField(null=True, blank=True)
    s_BackgroundColor = models.TextField(null=True, blank=True)
    s_LabelColor = models.TextField(null=True, blank=True)
    s_SeasonLabelColor = models.TextField(null=True, blank=True)
    s_SeasonBackColor = models.TextField(null=True, blank=True)
    i_SortOrder = models.IntegerField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'TicketCollectionData {self.pk}'

class CharacterData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    i_Area = models.IntegerField(null=True, blank=True)
    s_BundleName = models.TextField(null=True, blank=True)
    s_Name_KO = models.TextField(null=True, blank=True)
    s_Name_EN = models.TextField(null=True, blank=True)
    s_Name_JA = models.TextField(null=True, blank=True)
    s_Name_ZH_CHS = models.TextField(null=True, blank=True)
    s_Name_ZH_CHT = models.TextField(null=True, blank=True)
    s_Name_VI = models.TextField(null=True, blank=True)
    s_Name_ES = models.TextField(null=True, blank=True)
    s_Name_IT = models.TextField(null=True, blank=True)
    s_Name_ID = models.TextField(null=True, blank=True)
    s_Name_TH = models.TextField(null=True, blank=True)
    s_Name_PT = models.TextField(null=True, blank=True)
    s_Name_HI = models.TextField(null=True, blank=True)
    s_Description_KO = models.TextField(null=True, blank=True)
    s_Description_EN = models.TextField(null=True, blank=True)
    s_Description_JA = models.TextField(null=True, blank=True)
    s_Description_ZH_CHS = models.TextField(null=True, blank=True)
    s_Description_ZH_CHT = models.TextField(null=True, blank=True)
    s_Description_VI = models.TextField(null=True, blank=True)
    s_Description_ES = models.TextField(null=True, blank=True)
    s_Description_IT = models.TextField(null=True, blank=True)
    s_Description_ID = models.TextField(null=True, blank=True)
    s_Description_TH = models.TextField(null=True, blank=True)
    s_Description_PT = models.TextField(null=True, blank=True)
    s_Description_HI = models.TextField(null=True, blank=True)
    s_ResourceName = models.TextField(null=True, blank=True)
    i_MaxLevel = models.BigIntegerField(null=True, blank=True)
    d_LevelRate = models.FloatField(null=True, blank=True)
    d_LateCost = models.FloatField(null=True, blank=True)
    d_Cost = models.FloatField(null=True, blank=True)
    d_CostIncreaseValue = models.FloatField(null=True, blank=True)
    d_CostValueConstant = models.FloatField(null=True, blank=True)
    d_Amount = models.FloatField(null=True, blank=True)
    d_AmountIncreaseValue = models.FloatField(null=True, blank=True)
    d_AmountValueConstant = models.FloatField(null=True, blank=True)
    d_BonusAmountIncreaseRate = models.FloatField(null=True, blank=True)
    i_UnlockLevel = models.BigIntegerField(null=True, blank=True)
    d_UnlockCost = models.FloatField(null=True, blank=True)
    i_RequirementFollowerId_1 = models.BigIntegerField(null=True, blank=True)
    i_RequirementFollowerId_2 = models.BigIntegerField(null=True, blank=True)
    i_RequirementPropId_1 = models.BigIntegerField(null=True, blank=True)
    i_RequirementPropId_2 = models.BigIntegerField(null=True, blank=True)
    i_RequirementPropCount = models.BigIntegerField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'CharacterData {self.pk}'

class SamSeckEventData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    s_Description_KO = models.TextField(null=True, blank=True)
    s_Description_EN = models.TextField(null=True, blank=True)
    s_Description_JA = models.TextField(null=True, blank=True)
    s_Description_ZH_CHS = models.TextField(null=True, blank=True)
    s_Description_ZH_CHT = models.TextField(null=True, blank=True)
    s_Description_VI = models.TextField(null=True, blank=True)
    s_Description_ES = models.TextField(null=True, blank=True)
    s_Description_IT = models.TextField(null=True, blank=True)
    s_Description_ID = models.TextField(null=True, blank=True)
    s_Description_TH = models.TextField(null=True, blank=True)
    s_Description_PT = models.TextField(null=True, blank=True)
    s_Description_HI = models.TextField(null=True, blank=True)
    s_ConditionType = models.TextField(null=True, blank=True)
    d_Condition = models.FloatField(null=True, blank=True)
    i_MailRewardID = models.BigIntegerField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'SamSeckEventData {self.pk}'

class LocalPushData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    s_LocalPushRegisterType = models.TextField(null=True, blank=True)
    i_TimeForSeconds = models.BigIntegerField(null=True, blank=True)
    b_IsMultipleJson = models.IntegerField(null=True, blank=True)
    s_JsonMessage_KO = models.TextField(null=True, blank=True)
    s_JsonMessage_EN = models.TextField(null=True, blank=True)
    s_JsonMessage_JA = models.TextField(null=True, blank=True)
    s_JsonMessage_ZH_CHS = models.TextField(null=True, blank=True)
    s_JsonMessage_ZH_CHT = models.TextField(null=True, blank=True)
    s_JsonMessage_VI = models.TextField(null=True, blank=True)
    s_JsonMessage_ES = models.TextField(null=True, blank=True)
    s_JsonMessage_IT = models.TextField(null=True, blank=True)
    s_JsonMessage_ID = models.TextField(null=True, blank=True)
    s_JsonMessage_TH = models.TextField(null=True, blank=True)
    s_JsonMessage_PT = models.TextField(null=True, blank=True)
    s_JsonMessage_HI = models.TextField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'LocalPushData {self.pk}'

class FollowerQuestData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    i_UnlockFollowerID = models.IntegerField(null=True, blank=True)
    i_UnlockFollowerLevel = models.IntegerField(null=True, blank=True)
    s_ConditionType1 = models.TextField(null=True, blank=True)
    d_Condition1_1 = models.FloatField(null=True, blank=True)
    d_Condition1_2 = models.FloatField(null=True, blank=True)
    s_ConditionType2 = models.TextField(null=True, blank=True)
    d_Condition2_1 = models.FloatField(null=True, blank=True)
    d_Condition2_2 = models.FloatField(null=True, blank=True)
    s_ConditionType3 = models.TextField(null=True, blank=True)
    d_Condition3_1 = models.FloatField(null=True, blank=True)
    d_Condition3_2 = models.FloatField(null=True, blank=True)
    i_RewardGroup1 = models.IntegerField(null=True, blank=True)
    i_RewardGroup2 = models.IntegerField(null=True, blank=True)
    i_RewardGroup3 = models.IntegerField(null=True, blank=True)
    s_Description_KO = models.TextField(null=True, blank=True)
    s_Description_EN = models.TextField(null=True, blank=True)
    s_Description_ZH_CHS = models.TextField(null=True, blank=True)
    s_Description_ZH_CHT = models.TextField(null=True, blank=True)
    s_Description_JA = models.TextField(null=True, blank=True)
    s_Description_VI = models.TextField(null=True, blank=True)
    s_Description_ES = models.TextField(null=True, blank=True)
    s_Description_IT = models.TextField(null=True, blank=True)
    s_Description_ID = models.TextField(null=True, blank=True)
    s_Description_TH = models.TextField(null=True, blank=True)
    s_Description_PT = models.TextField(null=True, blank=True)
    s_Description_HI = models.TextField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)
    i_Type = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'FollowerQuestData {self.pk}'

class PropLevelData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    i_PropId = models.BigIntegerField(null=True, blank=True)
    i_Level = models.BigIntegerField(null=True, blank=True)
    d_Cost = models.FloatField(null=True, blank=True)
    i_PerksId = models.BigIntegerField(null=True, blank=True)
    d_PerksValue = models.FloatField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'PropLevelData {self.pk}'

class FollowerProfileData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    s_Name_KO = models.TextField(null=True, blank=True)
    s_Name_EN = models.TextField(null=True, blank=True)
    s_Name_JA = models.TextField(null=True, blank=True)
    s_Name_ZH_CHS = models.TextField(null=True, blank=True)
    s_Name_ZH_CHT = models.TextField(null=True, blank=True)
    s_Name_VI = models.TextField(null=True, blank=True)
    s_Name_ES = models.TextField(null=True, blank=True)
    s_Name_IT = models.TextField(null=True, blank=True)
    s_Name_ID = models.TextField(null=True, blank=True)
    s_Name_TH = models.TextField(null=True, blank=True)
    s_Name_PT = models.TextField(null=True, blank=True)
    s_Name_HI = models.TextField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)
    s_GiftItemID = models.TextField(null=True, blank=True)
    b_IsVisible = models.IntegerField(null=True, blank=True)
    s_BackgroundColor = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'FollowerProfileData {self.pk}'

class PassGoodsShopData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    i_TicketID = models.IntegerField(null=True, blank=True)
    i_GoodsTicketID = models.IntegerField(null=True, blank=True)
    i_ShopID = models.IntegerField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)
    i_SaleShopID = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'PassGoodsShopData {self.pk}'

class FollowerGiftItemData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    i_GiftType = models.IntegerField(null=True, blank=True)
    d_Value = models.BigIntegerField(null=True, blank=True)
    i_Limit = models.IntegerField(null=True, blank=True)
    s_ResourceName = models.TextField(null=True, blank=True)
    s_Name_KO = models.TextField(null=True, blank=True)
    s_Name_EN = models.TextField(null=True, blank=True)
    s_Name_JA = models.TextField(null=True, blank=True)
    s_Name_ZH_CHS = models.TextField(null=True, blank=True)
    s_Name_ZH_CHT = models.TextField(null=True, blank=True)
    s_Name_VI = models.TextField(null=True, blank=True)
    s_Name_ES = models.TextField(null=True, blank=True)
    s_Name_IT = models.TextField(null=True, blank=True)
    s_Name_ID = models.TextField(null=True, blank=True)
    s_Name_TH = models.TextField(null=True, blank=True)
    s_Name_PT = models.TextField(null=True, blank=True)
    s_Name_HI = models.TextField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'FollowerGiftItemData {self.pk}'

class FollowerProfileLevelData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    i_ProfileID = models.IntegerField(null=True, blank=True)
    i_Level = models.IntegerField(null=True, blank=True)
    d_RequireEXP = models.BigIntegerField(null=True, blank=True)
    i_RewardGroup = models.IntegerField(null=True, blank=True)
    s_UnlockInformation = models.TextField(null=True, blank=True)
    i_AddCandy = models.IntegerField(null=True, blank=True)
    i_UnlockStoryID = models.IntegerField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'FollowerProfileLevelData {self.pk}'

class AdListData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    i_Category = models.IntegerField(null=True, blank=True)
    s_ConditionType1 = models.TextField(null=True, blank=True)
    s_ConditionValue1 = models.TextField(null=True, blank=True)
    s_ConditionType2 = models.TextField(null=True, blank=True)
    s_ConditionValue2 = models.TextField(null=True, blank=True)
    s_ResourceName = models.TextField(null=True, blank=True)
    s_Name_KO = models.TextField(null=True, blank=True)
    s_Name_EN = models.TextField(null=True, blank=True)
    s_Name_JA = models.TextField(null=True, blank=True)
    s_Name_ZH_CHS = models.TextField(null=True, blank=True)
    s_Name_ZH_CHT = models.TextField(null=True, blank=True)
    s_Name_VI = models.TextField(null=True, blank=True)
    s_Name_ES = models.TextField(null=True, blank=True)
    s_Name_IT = models.TextField(null=True, blank=True)
    s_Name_ID = models.TextField(null=True, blank=True)
    s_Name_TH = models.TextField(null=True, blank=True)
    s_Name_PT = models.TextField(null=True, blank=True)
    s_Name_HI = models.TextField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)
    s_RewardType = models.TextField(null=True, blank=True)
    i_RewardGroup = models.IntegerField(null=True, blank=True)
    s_ExtraValue = models.TextField(null=True, blank=True)
    s_AdType = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'AdListData {self.pk}'

class ChThirdStageData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    i_Chapter = models.IntegerField(null=True, blank=True)
    i_StageIndex = models.IntegerField(null=True, blank=True)
    i_RewardGroupID = models.IntegerField(null=True, blank=True)
    i_GoalScore1 = models.IntegerField(null=True, blank=True)
    i_GoalScore2 = models.IntegerField(null=True, blank=True)
    i_GoalScore3 = models.IntegerField(null=True, blank=True)
    s_BonusProfileID = models.TextField(null=True, blank=True)
    s_Name_KO = models.TextField(null=True, blank=True)
    s_Name_EN = models.TextField(null=True, blank=True)
    s_Name_JA = models.TextField(null=True, blank=True)
    s_Name_ZH_CHS = models.TextField(null=True, blank=True)
    s_Name_ZH_CHT = models.TextField(null=True, blank=True)
    s_Name_VI = models.TextField(null=True, blank=True)
    s_Name_ES = models.TextField(null=True, blank=True)
    s_Name_IT = models.TextField(null=True, blank=True)
    s_Name_ID = models.TextField(null=True, blank=True)
    s_Name_TH = models.TextField(null=True, blank=True)
    s_Name_PT = models.TextField(null=True, blank=True)
    s_Name_HI = models.TextField(null=True, blank=True)
    s_Description_KO = models.TextField(null=True, blank=True)
    s_Description_EN = models.TextField(null=True, blank=True)
    s_Description_JA = models.TextField(null=True, blank=True)
    s_Description_ZH_CHS = models.TextField(null=True, blank=True)
    s_Description_ZH_CHT = models.TextField(null=True, blank=True)
    s_Description_VI = models.TextField(null=True, blank=True)
    s_Description_ES = models.TextField(null=True, blank=True)
    s_Description_IT = models.TextField(null=True, blank=True)
    s_Description_ID = models.TextField(null=True, blank=True)
    s_Description_TH = models.TextField(null=True, blank=True)
    s_Description_PT = models.TextField(null=True, blank=True)
    s_Description_HI = models.TextField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)
    s_StageType = models.TextField(null=True, blank=True)
    i_StoryID = models.IntegerField(null=True, blank=True)
    i_BonusMusicID = models.IntegerField(null=True, blank=True)
    s_PercentRewardGroupID = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'ChThirdStageData {self.pk}'

class ChThirdScoreData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    i_Level = models.IntegerField(null=True, blank=True)
    i_CharacterScore = models.IntegerField(null=True, blank=True)
    i_FollowerScore = models.IntegerField(null=True, blank=True)
    i_MusicScore = models.IntegerField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'ChThirdScoreData {self.pk}'

class ChThirdChapterData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    i_unlockLevel = models.IntegerField(null=True, blank=True)
    i_RewardGroupID1 = models.IntegerField(null=True, blank=True)
    i_GoalStar1 = models.IntegerField(null=True, blank=True)
    i_RewardGroupID2 = models.IntegerField(null=True, blank=True)
    i_GoalStar2 = models.IntegerField(null=True, blank=True)
    i_RewardGroupID3 = models.IntegerField(null=True, blank=True)
    i_GoalStar3 = models.IntegerField(null=True, blank=True)
    s_Name_KO = models.TextField(null=True, blank=True)
    s_Name_EN = models.TextField(null=True, blank=True)
    s_Name_JA = models.TextField(null=True, blank=True)
    s_Name_ZH_CHS = models.TextField(null=True, blank=True)
    s_Name_ZH_CHT = models.TextField(null=True, blank=True)
    s_Name_VI = models.TextField(null=True, blank=True)
    s_Name_ES = models.TextField(null=True, blank=True)
    s_Name_IT = models.TextField(null=True, blank=True)
    s_Name_ID = models.TextField(null=True, blank=True)
    s_Name_TH = models.TextField(null=True, blank=True)
    s_Name_PT = models.TextField(null=True, blank=True)
    s_Name_HI = models.TextField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'ChThirdChapterData {self.pk}'

class PercentData(models.Model):
    i_GroupID = models.IntegerField(null=True, blank=True)
    i_RewardType = models.IntegerField(null=True, blank=True)
    i_RewardID = models.IntegerField(null=True, blank=True)
    l_RewardQuantity = models.IntegerField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)
    i_id = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'PercentData {self.pk}'

class AdLevelData(models.Model):
    i_GroupID = models.IntegerField(null=True, blank=True)
    i_Level = models.IntegerField(null=True, blank=True)
    i_RequireEXP = models.IntegerField(null=True, blank=True)
    i_RewardGroup = models.IntegerField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)
    i_id = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'AdLevelData {self.pk}'

class EventListData(models.Model):
    idx = models.IntegerField(null=True, blank=True)
    event_type = models.TextField(null=True, blank=True)
    start_date = models.TextField(null=True, blank=True)
    end_date = models.TextField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'EventListData {self.pk}'

class SelectRewardData(models.Model):
    i_id = models.IntegerField(null=True, blank=True)
    i_GroupId = models.IntegerField(null=True, blank=True)
    i_RewardGroupId = models.IntegerField(null=True, blank=True)
    i_AltRewardGroupId = models.IntegerField(null=True, blank=True)
    b_IsActive = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'SelectRewardData {self.pk}'

