#
# Autogenerated by Thrift Compiler (0.22.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec
from uuid import UUID

import sys
import tapsonic.general.ttypes

from thrift.transport import TTransport
all_structs = []


class buyVarietyStoreDataInfo(object):
    """
    Attributes:
     - u_seq
     - u_id
     - uuid
     - device_uuid
     - idx

    """
    thrift_spec = None


    def __init__(self, u_seq = None, u_id = None, uuid = None, device_uuid = None, idx = None,):
        self.u_seq = u_seq
        self.u_id = u_id
        self.uuid = uuid
        self.device_uuid = device_uuid
        self.idx = idx

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.u_seq = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRING:
                    self.u_id = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.uuid = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRING:
                    self.device_uuid = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.I32:
                    self.idx = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('buyVarietyStoreDataInfo')
        if self.u_seq is not None:
            oprot.writeFieldBegin('u_seq', TType.I32, 1)
            oprot.writeI32(self.u_seq)
            oprot.writeFieldEnd()
        if self.u_id is not None:
            oprot.writeFieldBegin('u_id', TType.STRING, 2)
            oprot.writeString(self.u_id.encode('utf-8') if sys.version_info[0] == 2 else self.u_id)
            oprot.writeFieldEnd()
        if self.uuid is not None:
            oprot.writeFieldBegin('uuid', TType.STRING, 3)
            oprot.writeString(self.uuid.encode('utf-8') if sys.version_info[0] == 2 else self.uuid)
            oprot.writeFieldEnd()
        if self.device_uuid is not None:
            oprot.writeFieldBegin('device_uuid', TType.STRING, 4)
            oprot.writeString(self.device_uuid.encode('utf-8') if sys.version_info[0] == 2 else self.device_uuid)
            oprot.writeFieldEnd()
        if self.idx is not None:
            oprot.writeFieldBegin('idx', TType.I32, 5)
            oprot.writeI32(self.idx)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class buyVarietyStore(object):
    """
    Attributes:
     - call
     - data
     - common_data

    """
    thrift_spec = None


    def __init__(self, call = None, data = None, common_data = None,):
        self.call = call
        self.data = data
        self.common_data = common_data

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.call = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.data = buyVarietyStoreDataInfo()
                    self.data.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRUCT:
                    self.common_data = tapsonic.general.ttypes.paramData()
                    self.common_data.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('buyVarietyStore')
        if self.call is not None:
            oprot.writeFieldBegin('call', TType.STRING, 1)
            oprot.writeString(self.call.encode('utf-8') if sys.version_info[0] == 2 else self.call)
            oprot.writeFieldEnd()
        if self.data is not None:
            oprot.writeFieldBegin('data', TType.STRUCT, 2)
            self.data.write(oprot)
            oprot.writeFieldEnd()
        if self.common_data is not None:
            oprot.writeFieldBegin('common_data', TType.STRUCT, 3)
            self.common_data.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class buyVarietyStoreRetDataInfo(object):
    """
    Attributes:
     - u_cp
     - u_candy
     - reward_type
     - reward_id
     - reward_value
     - status

    """
    thrift_spec = None


    def __init__(self, u_cp = None, u_candy = None, reward_type = None, reward_id = None, reward_value = None, status = None,):
        self.u_cp = u_cp
        self.u_candy = u_candy
        self.reward_type = reward_type
        self.reward_id = reward_id
        self.reward_value = reward_value
        self.status = status

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.u_cp = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.DOUBLE:
                    self.u_candy = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I16:
                    self.reward_type = iprot.readI16()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I32:
                    self.reward_id = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.I64:
                    self.reward_value = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.STRING:
                    self.status = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('buyVarietyStoreRetDataInfo')
        if self.u_cp is not None:
            oprot.writeFieldBegin('u_cp', TType.I64, 1)
            oprot.writeI64(self.u_cp)
            oprot.writeFieldEnd()
        if self.u_candy is not None:
            oprot.writeFieldBegin('u_candy', TType.DOUBLE, 2)
            oprot.writeDouble(self.u_candy)
            oprot.writeFieldEnd()
        if self.reward_type is not None:
            oprot.writeFieldBegin('reward_type', TType.I16, 3)
            oprot.writeI16(self.reward_type)
            oprot.writeFieldEnd()
        if self.reward_id is not None:
            oprot.writeFieldBegin('reward_id', TType.I32, 4)
            oprot.writeI32(self.reward_id)
            oprot.writeFieldEnd()
        if self.reward_value is not None:
            oprot.writeFieldBegin('reward_value', TType.I64, 5)
            oprot.writeI64(self.reward_value)
            oprot.writeFieldEnd()
        if self.status is not None:
            oprot.writeFieldBegin('status', TType.STRING, 6)
            oprot.writeString(self.status.encode('utf-8') if sys.version_info[0] == 2 else self.status)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class buyVarietyStoreReturn(object):
    """
    Attributes:
     - error
     - server_time
     - mode
     - call
     - data
     - maintenance

    """
    thrift_spec = None


    def __init__(self, error = None, server_time = None, mode = None, call = None, data = None, maintenance = None,):
        self.error = error
        self.server_time = server_time
        self.mode = mode
        self.call = call
        self.data = data
        self.maintenance = maintenance

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.error = tapsonic.general.ttypes.errorRetCode()
                    self.error.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.server_time = tapsonic.general.ttypes.serverTimeRet()
                    self.server_time.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.mode = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRING:
                    self.call = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.STRUCT:
                    self.data = buyVarietyStoreRetDataInfo()
                    self.data.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.STRUCT:
                    self.maintenance = tapsonic.general.ttypes.maintenanceData()
                    self.maintenance.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('buyVarietyStoreReturn')
        if self.error is not None:
            oprot.writeFieldBegin('error', TType.STRUCT, 1)
            self.error.write(oprot)
            oprot.writeFieldEnd()
        if self.server_time is not None:
            oprot.writeFieldBegin('server_time', TType.STRUCT, 2)
            self.server_time.write(oprot)
            oprot.writeFieldEnd()
        if self.mode is not None:
            oprot.writeFieldBegin('mode', TType.STRING, 3)
            oprot.writeString(self.mode.encode('utf-8') if sys.version_info[0] == 2 else self.mode)
            oprot.writeFieldEnd()
        if self.call is not None:
            oprot.writeFieldBegin('call', TType.STRING, 4)
            oprot.writeString(self.call.encode('utf-8') if sys.version_info[0] == 2 else self.call)
            oprot.writeFieldEnd()
        if self.data is not None:
            oprot.writeFieldBegin('data', TType.STRUCT, 5)
            self.data.write(oprot)
            oprot.writeFieldEnd()
        if self.maintenance is not None:
            oprot.writeFieldBegin('maintenance', TType.STRUCT, 6)
            self.maintenance.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(buyVarietyStoreDataInfo)
buyVarietyStoreDataInfo.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'u_seq', None, None, ),  # 1
    (2, TType.STRING, 'u_id', 'UTF8', None, ),  # 2
    (3, TType.STRING, 'uuid', 'UTF8', None, ),  # 3
    (4, TType.STRING, 'device_uuid', 'UTF8', None, ),  # 4
    (5, TType.I32, 'idx', None, None, ),  # 5
)
all_structs.append(buyVarietyStore)
buyVarietyStore.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'call', 'UTF8', None, ),  # 1
    (2, TType.STRUCT, 'data', [buyVarietyStoreDataInfo, None], None, ),  # 2
    (3, TType.STRUCT, 'common_data', [tapsonic.general.ttypes.paramData, None], None, ),  # 3
)
all_structs.append(buyVarietyStoreRetDataInfo)
buyVarietyStoreRetDataInfo.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'u_cp', None, None, ),  # 1
    (2, TType.DOUBLE, 'u_candy', None, None, ),  # 2
    (3, TType.I16, 'reward_type', None, None, ),  # 3
    (4, TType.I32, 'reward_id', None, None, ),  # 4
    (5, TType.I64, 'reward_value', None, None, ),  # 5
    (6, TType.STRING, 'status', 'UTF8', None, ),  # 6
)
all_structs.append(buyVarietyStoreReturn)
buyVarietyStoreReturn.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'error', [tapsonic.general.ttypes.errorRetCode, None], None, ),  # 1
    (2, TType.STRUCT, 'server_time', [tapsonic.general.ttypes.serverTimeRet, None], None, ),  # 2
    (3, TType.STRING, 'mode', 'UTF8', None, ),  # 3
    (4, TType.STRING, 'call', 'UTF8', None, ),  # 4
    (5, TType.STRUCT, 'data', [buyVarietyStoreRetDataInfo, None], None, ),  # 5
    (6, TType.STRUCT, 'maintenance', [tapsonic.general.ttypes.maintenanceData, None], None, ),  # 6
)
fix_spec(all_structs)
del all_structs
