# Generated by Django 6.0.1 on 2026-05-25 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.BigIntegerField(unique=True)),
                ('event_name', models.CharField(max_length=128)),
                ('event_type', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('u_seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('u_id', models.CharField(blank=True, max_length=128, null=True)),
                ('uuid', models.CharField(blank=True, max_length=128, null=True)),
                ('device_uuid', models.CharField(blank=True, max_length=128, null=True)),
                ('u_cp', models.BigIntegerField(default=0)),
                ('u_nickname', models.CharField(blank=True, max_length=128, null=True)),
                ('u_candy', models.FloatField(default=0)),
                ('u_selected_costume_id', models.BigIntegerField(default=0)),
                ('u_selected_music_id', models.BigIntegerField(default=0)),
                ('u_last_login', models.DateTimeField(null=True)),
                ('u_last_communication', models.DateTimeField(null=True)),
                ('u_save_date', models.DateTimeField(null=True)),
                ('u_tutorial_step', models.SmallIntegerField(default=0)),
                ('u_review_popup', models.CharField(default='N', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_idx', models.BigIntegerField()),
                ('reward_num', models.IntegerField()),
                ('reward_type', models.IntegerField()),
                ('reward_id', models.IntegerField()),
                ('reward_value', models.IntegerField()),
                ('s_CustomIconType', models.CharField(max_length=128)),
                ('s_CustomIconSprite', models.CharField(max_length=128)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='gameapi.event')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('rewarded_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.BigIntegerField()),
                ('i_Level', models.BigIntegerField(default=1)),
                ('d_Quantity', models.FloatField(default=0)),
                ('s_Quantity', models.CharField(blank=True, max_length=255)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserAdLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.IntegerField()),
                ('i_Level', models.IntegerField(default=1)),
                ('i_EXP', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_levels', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserAdList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.IntegerField()),
                ('i_Count', models.IntegerField(default=0)),
                ('i_TotalCount', models.IntegerField(default=0)),
                ('i_LastViewTime', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_lists', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserAreaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_area_num', models.SmallIntegerField()),
                ('d_Like', models.FloatField(default=0)),
                ('i_UserFanCount', models.BigIntegerField(default=0)),
                ('i_UserFanGrade', models.SmallIntegerField(default=0)),
                ('i_SelectedCostumeId', models.BigIntegerField(default=0)),
                ('i_SelectedMusicId', models.BigIntegerField(default=0)),
                ('i_SelectedGuitarId', models.BigIntegerField(default=0)),
                ('d_Candy', models.FloatField(default=0)),
                ('s_TutorialList', models.CharField(blank=True, max_length=128)),
                ('s_Gp1', models.TextField(blank=True, null=True)),
                ('s_Gp2', models.TextField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserBuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.BigIntegerField()),
                ('i_Level', models.BigIntegerField(default=0)),
                ('i_ActiveTime', models.BigIntegerField(default=0)),
                ('i_EndTime', models.BigIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buffs', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserCandyShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.BigIntegerField()),
                ('i_CurrentBuyCount', models.BigIntegerField(default=0)),
                ('i_TotalBuyCount', models.BigIntegerField(default=0)),
                ('l_LastBuyTick', models.FloatField(default=0)),
                ('upd_day', models.BigIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candy_shops', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.BigIntegerField()),
                ('i_Level', models.BigIntegerField(default=1)),
                ('i_BonusLevel', models.BigIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserChThirdStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.IntegerField()),
                ('i_ChapterId', models.IntegerField(default=0)),
                ('i_StageIndex', models.IntegerField(default=0)),
                ('i_Star', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ch_third_stages', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserCostume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.BigIntegerField()),
                ('i_Level', models.BigIntegerField(default=1)),
                ('i_BonusLevel', models.BigIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costumes', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserDailyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.BigIntegerField()),
                ('i_Level', models.BigIntegerField(default=1)),
                ('d_Quantity', models.BigIntegerField(default=0)),
                ('upd_date', models.CharField(blank=True, max_length=64)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_missions', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserEventPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_EventType', models.CharField(max_length=128)),
                ('i_DataID', models.BigIntegerField()),
                ('i_Point', models.BigIntegerField(default=0)),
                ('i_Step', models.BigIntegerField(default=0)),
                ('i_ADViewTime', models.BigIntegerField(default=0)),
                ('i_Version', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_points', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserEventReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_flg', models.CharField(default='N', max_length=5)),
                ('get_date', models.IntegerField()),
                ('event_reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rewards', to='gameapi.eventreward')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rewards', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.BigIntegerField()),
                ('i_Level', models.BigIntegerField(default=1)),
                ('i_BonusLevel', models.BigIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowerGiftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.IntegerField()),
                ('i_Value', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_gift_items', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.IntegerField()),
                ('i_Level', models.IntegerField(default=1)),
                ('d_Exp', models.BigIntegerField(default=0)),
                ('i_AddCandy', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_profiles', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowerProfileReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.IntegerField()),
                ('i_RewardLevel', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_profile_rewards', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowerQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.BigIntegerField()),
                ('i_CurrentID', models.BigIntegerField(default=0)),
                ('i_CompleteID', models.BigIntegerField(default=0)),
                ('d_ConditionValue1', models.FloatField(default=0)),
                ('d_ConditionValue2', models.FloatField(default=0)),
                ('d_ConditionValue3', models.FloatField(default=0)),
                ('i_RewardReceived1', models.SmallIntegerField(default=0)),
                ('i_RewardReceived2', models.SmallIntegerField(default=0)),
                ('i_RewardReceived3', models.SmallIntegerField(default=0)),
                ('i_isInfinity', models.SmallIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_quests', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowerQuestSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_CurrentID', models.BigIntegerField()),
                ('d_ConditionValue1', models.FloatField(default=0)),
                ('d_ConditionValue2', models.FloatField(default=0)),
                ('d_ConditionValue3', models.FloatField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_quest_saves', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserGuitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.BigIntegerField()),
                ('i_Level', models.BigIntegerField(default=1)),
                ('i_BonusLevel', models.BigIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guitars', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_MessengerChatRoomId', models.BigIntegerField()),
                ('i_LastConfirmIndex', models.BigIntegerField(default=0)),
                ('s_UnlockGroupList', models.TextField(blank=True, null=True)),
                ('l_UpdateTimeTicks', models.BigIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messengers', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.BigIntegerField()),
                ('i_Level', models.BigIntegerField(default=1)),
                ('i_BonusLevel', models.BigIntegerField(default=0)),
                ('b_EncoreBonusAppear', models.BigIntegerField(default=0)),
                ('l_EncoreBonusActivateTime', models.BigIntegerField(default=0)),
                ('i_EncoreBonusFollowerId', models.BigIntegerField(default=0)),
                ('i_ChThirdActiveTime', models.BigIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musics', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.BigIntegerField()),
                ('i_Level', models.BigIntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='props', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserSelectReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_GroupId', models.IntegerField()),
                ('i_RewardGroupId', models.IntegerField(default=0)),
                ('i_AltRewardGroupId', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_rewards', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.BigIntegerField()),
                ('i_Count', models.BigIntegerField(default=0)),
                ('i_TotalCount', models.BigIntegerField(default=0)),
                ('i_PurchaseTime', models.BigIntegerField(default=0)),
                ('upd_day', models.BigIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.BigIntegerField()),
                ('b_Activate', models.SmallIntegerField(default=0)),
                ('l_ActivateOnTicks', models.BigIntegerField(default=0)),
                ('l_ActivateOffTicks', models.BigIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscribeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_SubscribeID', models.BigIntegerField()),
                ('i_ActiveTime', models.BigIntegerField(default=0)),
                ('i_isActive', models.BigIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_lists', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscribePassReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_SubscribeID', models.BigIntegerField()),
                ('i_Type', models.BigIntegerField(default=0)),
                ('i_Step', models.BigIntegerField(default=0)),
                ('i_UpdateTime', models.BigIntegerField(default=0)),
                ('i_Version', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_pass_rewards', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserTicketCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.BigIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_collections', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='gameapi.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.BigIntegerField()),
                ('i_Level', models.BigIntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='gameapi.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='eventreward',
            constraint=models.UniqueConstraint(fields=('event', 'reward_idx'), name='event_reward_unique'),
        ),
        migrations.AddConstraint(
            model_name='usereventreward',
            constraint=models.UniqueConstraint(fields=('player', 'event_reward'), name='user_event_reward_unique'),
        ),
    ]
