# Generated by Django 5.2.7 on 2026-06-03 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('notice_type', models.SmallIntegerField(default=0)),
                ('title_ko', models.CharField(blank=True, max_length=255)),
                ('memo_ko', models.TextField(blank=True)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('memo_en', models.TextField(blank=True)),
                ('title_jp', models.CharField(blank=True, max_length=255)),
                ('memo_jp', models.TextField(blank=True)),
                ('title_zh_chs', models.CharField(blank=True, max_length=255)),
                ('memo_zh_chs', models.TextField(blank=True)),
                ('title_zh_cht', models.CharField(blank=True, max_length=255)),
                ('memo_zh_cht', models.TextField(blank=True)),
                ('title_vi', models.CharField(blank=True, max_length=255)),
                ('memo_vi', models.TextField(blank=True)),
                ('title_es', models.CharField(blank=True, max_length=255)),
                ('memo_es', models.TextField(blank=True)),
                ('title_it', models.CharField(blank=True, max_length=255)),
                ('memo_it', models.TextField(blank=True)),
                ('title_id', models.CharField(blank=True, max_length=255)),
                ('memo_id', models.TextField(blank=True)),
                ('title_th', models.CharField(blank=True, max_length=255)),
                ('memo_th', models.TextField(blank=True)),
                ('title_pt', models.CharField(blank=True, max_length=255)),
                ('memo_pt', models.TextField(blank=True)),
                ('title_hi', models.CharField(blank=True, max_length=255)),
                ('memo_hi', models.TextField(blank=True)),
                ('have_reward', models.SmallIntegerField(default=0)),
                ('unlimit_flg', models.SmallIntegerField(default=0)),
                ('create_time', models.BigIntegerField(default=0)),
                ('del_time', models.BigIntegerField(default=0)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('image_resource_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_RewardType', models.IntegerField()),
                ('i_RewardId', models.IntegerField()),
                ('d_RewardQuantity', models.FloatField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gameapi.post')),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=0)),
                ('flg', models.SmallIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='gameapi.player')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameapi.post')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'post'), name='user_post_unique')],
            },
        ),
    ]
