# Generated by Django 5.2.7 on 2026-06-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0002_post_postitem_userpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerGiftItemData',
            fields=[
                ('i_id', models.IntegerField(primary_key=True, serialize=False)),
                ('i_GiftType', models.IntegerField(default=0)),
                ('d_Value', models.BigIntegerField(default=0)),
                ('i_Limit', models.IntegerField(default=0)),
                ('s_Name_EN', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowerProfileLevelData',
            fields=[
                ('i_id', models.IntegerField(primary_key=True, serialize=False)),
                ('i_ProfileID', models.IntegerField()),
                ('i_Level', models.IntegerField()),
                ('d_RequireEXP', models.BigIntegerField(default=0)),
                ('i_AddCandy', models.IntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('i_ProfileID', 'i_Level'), name='follower_profile_level_unique')],
            },
        ),
    ]
