# Generated by Django 5.2.7 on 2026-06-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0003_followergiftitemdata_followerprofileleveldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementData',
            fields=[
                ('i_id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_RewardType', models.CharField(max_length=64)),
                ('i_Reward_1', models.BigIntegerField(default=0)),
                ('i_Reward_2', models.BigIntegerField(default=0)),
                ('i_Reward_3', models.BigIntegerField(default=0)),
                ('i_Reward_4', models.BigIntegerField(default=0)),
                ('i_Reward_5', models.BigIntegerField(default=0)),
                ('i_Reward_6', models.BigIntegerField(default=0)),
                ('i_Reward_7', models.BigIntegerField(default=0)),
                ('i_Reward_8', models.BigIntegerField(default=0)),
                ('i_Reward_9', models.BigIntegerField(default=0)),
                ('i_Reward_10', models.BigIntegerField(default=0)),
                ('i_Reward_11', models.BigIntegerField(default=0)),
                ('i_Reward_12', models.BigIntegerField(default=0)),
                ('i_Reward_13', models.BigIntegerField(default=0)),
                ('i_Reward_14', models.BigIntegerField(default=0)),
                ('i_Reward_15', models.BigIntegerField(default=0)),
                ('i_Reward_16', models.BigIntegerField(default=0)),
                ('i_Reward_17', models.BigIntegerField(default=0)),
                ('i_Reward_18', models.BigIntegerField(default=0)),
                ('i_Reward_19', models.BigIntegerField(default=0)),
                ('i_Reward_20', models.BigIntegerField(default=0)),
                ('i_MaxLevel', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMissionData',
            fields=[
                ('i_id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_RewardType', models.CharField(max_length=64)),
                ('i_Reward_1', models.IntegerField(default=0)),
            ],
        ),
    ]
