# Generated by Django 5.2.7 on 2026-06-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0004_achievementdata_dailymissiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='u_cookie',
            field=models.BigIntegerField(default=0),
        ),
    ]
