# Generated by Django 6.0.1 on 2026-06-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0005_player_u_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='i_Level',
            field=models.BigIntegerField(default=1),
        ),
    ]
