# Generated by Django 5.2.7 on 2026-06-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0006_userskill_i_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardGroupData',
            fields=[
                ('i_id', models.IntegerField(primary_key=True, serialize=False)),
                ('i_Group', models.IntegerField(default=0)),
                ('i_RewardType', models.IntegerField(default=0)),
                ('i_RewardID', models.IntegerField(default=0)),
                ('l_RewardQuantity', models.FloatField(default=0)),
                ('i_BuyFirstQuantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='followerprofileleveldata',
            name='i_RewardGroup',
            field=models.IntegerField(default=0),
        ),
    ]
