# Generated by Django 5.2.7 on 2026-06-05 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0007_rewardgroupdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSamSeckEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_idx', models.IntegerField()),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samseck_events', to='gameapi.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'reward_idx'), name='user_samseck_reward_unique')],
            },
        ),
    ]
