# Generated by Django 5.2.7 on 2026-06-05 10:28

from django.db import migrations
import time

def populate_samseck_posts(apps, schema_editor):
    Post = apps.get_model('gameapi', 'Post')
    PostItem = apps.get_model('gameapi', 'PostItem')
    
    rewards = {
        33301: (3, 13, 1.0),
        33302: (9, 10, 1.0),
        33303: (1, 1, 333.0)
    }
    
    for post_id, (r_type, r_id, r_qty) in rewards.items():
        post, created = Post.objects.get_or_create(
            idx=post_id,
            defaults=dict(
                notice_type=0,
                title_ko="삼색이의 333 이벤트 보상",
                memo_ko="삼색이의 333 이벤트 보상입니다.",
                title_en="Calico Cat's Meowfest Reward",
                memo_en="This is Calico Cat's Meowfest Reward.",
                title_jp="ミケの333イベント報酬",
                memo_jp="ミケの333イベント報酬です。",
                title_zh_chs="三色猫的喵喵活动奖励",
                memo_zh_chs="这是三色猫的喵喵活动奖励。",
                title_zh_cht="三色貓的喵喵活動獎勵",
                memo_zh_cht="這是三色貓的喵喵活動獎勵。",
                title_vi="Phần thưởng Sự kiện Meowfest của Calico Cat",
                memo_vi="Đây là Phần thưởng Sự kiện Meowfest của Calico Cat.",
                title_es="Recompensa del Festival miau del gato Calico",
                memo_es="Esta es la recompensa del Festival miau del gato Calico.",
                title_it="Ricompensa Miaofest di Calico",
                memo_it="Questa è la ricompensa per il Miaofest di Calico.",
                title_id="Hadiah Festival Kucing Calico Cat.",
                memo_id="Ini adalah Hadiah Festival Kucing Calico Cat.",
                title_th="รางวัลเทศกาลเหมียว ๆ ของแมวสามสี",
                memo_th="คือรางวัลเทศกาลเหมียว ๆ ของแมวสามสี",
                title_pt="Recompensa do Miaufest da Gata Malhada",
                memo_pt="Esta é a Recompensa do Miaufest da Gata Malhada.",
                title_hi="कैलिको कैट का म्याऊँफ़ेस्ट इनाम",
                memo_hi="यह इनाम कैलिको कैट को म्याऊँफ़ेस्ट में मिला है। ",
                have_reward=1,
                unlimit_flg=1,
                create_time=1768579563,
                del_time=2147451240,
            )
        )
        
        if created or not PostItem.objects.filter(post=post).exists():
            PostItem.objects.create(
                post=post,
                i_RewardType=r_type,
                i_RewardId=r_id,
                d_RewardQuantity=r_qty
            )


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0008_usersamseckevent'),
    ]

    operations = [
        migrations.RunPython(populate_samseck_posts),
    ]
