# Generated by Django 6.0.1 on 2026-06-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0100_import_static_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailymission',
            name='upd_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
