# Generated by Django 6.0.1 on 2026-06-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0101_alter_userdailymission_upd_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercandyshop',
            name='upd_day',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
