#
# Autogenerated by Thrift Compiler (0.22.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec
from uuid import UUID

import sys
import general.ttypes

from thrift.transport import TTransport
all_structs = []


class GetServerTimeResponseBody(object):
    """
    Attributes:
     - unix_time
     - local_time

    """
    thrift_spec = None


    def __init__(self, unix_time = None, local_time = None,):
        self.unix_time = unix_time
        self.local_time = local_time

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.unix_time = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I64:
                    self.local_time = iprot.readI64()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('GetServerTimeResponseBody')
        if self.unix_time is not None:
            oprot.writeFieldBegin('unix_time', TType.I64, 1)
            oprot.writeI64(self.unix_time)
            oprot.writeFieldEnd()
        if self.local_time is not None:
            oprot.writeFieldBegin('local_time', TType.I64, 2)
            oprot.writeI64(self.local_time)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class GetServerTimeResponse(object):
    """
    Attributes:
     - header
     - responseTime
     - service
     - method
     - body
     - footer

    """
    thrift_spec = None


    def __init__(self, header = None, responseTime = None, service = None, method = None, body = None, footer = None,):
        self.header = header
        self.responseTime = responseTime
        self.service = service
        self.method = method
        self.body = body
        self.footer = footer

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.header = general.ttypes.ResponseHeader()
                    self.header.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.responseTime = general.ttypes.ResponseTime()
                    self.responseTime.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.service = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRING:
                    self.method = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.STRUCT:
                    self.body = GetServerTimeResponseBody()
                    self.body.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.STRUCT:
                    self.footer = general.ttypes.ResponseFooter()
                    self.footer.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('GetServerTimeResponse')
        if self.header is not None:
            oprot.writeFieldBegin('header', TType.STRUCT, 1)
            self.header.write(oprot)
            oprot.writeFieldEnd()
        if self.responseTime is not None:
            oprot.writeFieldBegin('responseTime', TType.STRUCT, 2)
            self.responseTime.write(oprot)
            oprot.writeFieldEnd()
        if self.service is not None:
            oprot.writeFieldBegin('service', TType.STRING, 3)
            oprot.writeString(self.service.encode('utf-8') if sys.version_info[0] == 2 else self.service)
            oprot.writeFieldEnd()
        if self.method is not None:
            oprot.writeFieldBegin('method', TType.STRING, 4)
            oprot.writeString(self.method.encode('utf-8') if sys.version_info[0] == 2 else self.method)
            oprot.writeFieldEnd()
        if self.body is not None:
            oprot.writeFieldBegin('body', TType.STRUCT, 5)
            self.body.write(oprot)
            oprot.writeFieldEnd()
        if self.footer is not None:
            oprot.writeFieldBegin('footer', TType.STRUCT, 6)
            self.footer.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(GetServerTimeResponseBody)
GetServerTimeResponseBody.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'unix_time', None, None, ),  # 1
    (2, TType.I64, 'local_time', None, None, ),  # 2
)
all_structs.append(GetServerTimeResponse)
GetServerTimeResponse.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'header', [general.ttypes.ResponseHeader, None], None, ),  # 1
    (2, TType.STRUCT, 'responseTime', [general.ttypes.ResponseTime, None], None, ),  # 2
    (3, TType.STRING, 'service', 'UTF8', None, ),  # 3
    (4, TType.STRING, 'method', 'UTF8', None, ),  # 4
    (5, TType.STRUCT, 'body', [GetServerTimeResponseBody, None], None, ),  # 5
    (6, TType.STRUCT, 'footer', [general.ttypes.ResponseFooter, None], None, ),  # 6
)
fix_spec(all_structs)
del all_structs
