#
# Autogenerated by Thrift Compiler (0.22.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec
from uuid import UUID

import sys
import tapsonic.common.ttypes

from thrift.transport import TTransport
all_structs = []


class getPostDataInfo(object):
    """
    Attributes:
     - u_seq
     - u_id
     - uuid
     - device_uuid

    """
    thrift_spec = None


    def __init__(self, u_seq = None, u_id = None, uuid = None, device_uuid = None,):
        self.u_seq = u_seq
        self.u_id = u_id
        self.uuid = uuid
        self.device_uuid = device_uuid

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.u_seq = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRING:
                    self.u_id = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.uuid = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRING:
                    self.device_uuid = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('getPostDataInfo')
        if self.u_seq is not None:
            oprot.writeFieldBegin('u_seq', TType.I32, 1)
            oprot.writeI32(self.u_seq)
            oprot.writeFieldEnd()
        if self.u_id is not None:
            oprot.writeFieldBegin('u_id', TType.STRING, 2)
            oprot.writeString(self.u_id.encode('utf-8') if sys.version_info[0] == 2 else self.u_id)
            oprot.writeFieldEnd()
        if self.uuid is not None:
            oprot.writeFieldBegin('uuid', TType.STRING, 3)
            oprot.writeString(self.uuid.encode('utf-8') if sys.version_info[0] == 2 else self.uuid)
            oprot.writeFieldEnd()
        if self.device_uuid is not None:
            oprot.writeFieldBegin('device_uuid', TType.STRING, 4)
            oprot.writeString(self.device_uuid.encode('utf-8') if sys.version_info[0] == 2 else self.device_uuid)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class getPost(object):
    """
    Attributes:
     - call
     - data
     - common_data

    """
    thrift_spec = None


    def __init__(self, call = None, data = None, common_data = None,):
        self.call = call
        self.data = data
        self.common_data = common_data

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.call = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.data = getPostDataInfo()
                    self.data.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRUCT:
                    self.common_data = tapsonic.common.ttypes.paramData()
                    self.common_data.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('getPost')
        if self.call is not None:
            oprot.writeFieldBegin('call', TType.STRING, 1)
            oprot.writeString(self.call.encode('utf-8') if sys.version_info[0] == 2 else self.call)
            oprot.writeFieldEnd()
        if self.data is not None:
            oprot.writeFieldBegin('data', TType.STRUCT, 2)
            self.data.write(oprot)
            oprot.writeFieldEnd()
        if self.common_data is not None:
            oprot.writeFieldBegin('common_data', TType.STRUCT, 3)
            self.common_data.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class itemList(object):
    """
    Attributes:
     - i_RewardType
     - i_RewardId
     - d_RewardQuantity

    """
    thrift_spec = None


    def __init__(self, i_RewardType = None, i_RewardId = None, d_RewardQuantity = None,):
        self.i_RewardType = i_RewardType
        self.i_RewardId = i_RewardId
        self.d_RewardQuantity = d_RewardQuantity

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.i_RewardType = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.i_RewardId = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.DOUBLE:
                    self.d_RewardQuantity = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('itemList')
        if self.i_RewardType is not None:
            oprot.writeFieldBegin('i_RewardType', TType.I32, 1)
            oprot.writeI32(self.i_RewardType)
            oprot.writeFieldEnd()
        if self.i_RewardId is not None:
            oprot.writeFieldBegin('i_RewardId', TType.I32, 2)
            oprot.writeI32(self.i_RewardId)
            oprot.writeFieldEnd()
        if self.d_RewardQuantity is not None:
            oprot.writeFieldBegin('d_RewardQuantity', TType.DOUBLE, 3)
            oprot.writeDouble(self.d_RewardQuantity)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class getPostList(object):
    """
    Attributes:
     - idx
     - notice_type
     - title_ko
     - memo_ko
     - title_en
     - memo_en
     - title_jp
     - memo_jp
     - title_zh_chs
     - memo_zh_chs
     - title_zh_cht
     - memo_zh_cht
     - title_vi
     - memo_vi
     - title_es
     - memo_es
     - title_it
     - memo_it
     - title_id
     - memo_id
     - title_th
     - memo_th
     - title_pt
     - memo_pt
     - title_hi
     - memo_hi
     - have_reward
     - status
     - unlimit_flg
     - flg
     - create_time
     - del_time
     - item_list
     - url
     - image_resource_name

    """
    thrift_spec = None


    def __init__(self, idx = None, notice_type = None, title_ko = None, memo_ko = None, title_en = None, memo_en = None, title_jp = None, memo_jp = None, title_zh_chs = None, memo_zh_chs = None, title_zh_cht = None, memo_zh_cht = None, title_vi = None, memo_vi = None, title_es = None, memo_es = None, title_it = None, memo_it = None, title_id = None, memo_id = None, title_th = None, memo_th = None, title_pt = None, memo_pt = None, title_hi = None, memo_hi = None, have_reward = None, status = None, unlimit_flg = None, flg = None, create_time = None, del_time = None, item_list = None, url = None, image_resource_name = None,):
        self.idx = idx
        self.notice_type = notice_type
        self.title_ko = title_ko
        self.memo_ko = memo_ko
        self.title_en = title_en
        self.memo_en = memo_en
        self.title_jp = title_jp
        self.memo_jp = memo_jp
        self.title_zh_chs = title_zh_chs
        self.memo_zh_chs = memo_zh_chs
        self.title_zh_cht = title_zh_cht
        self.memo_zh_cht = memo_zh_cht
        self.title_vi = title_vi
        self.memo_vi = memo_vi
        self.title_es = title_es
        self.memo_es = memo_es
        self.title_it = title_it
        self.memo_it = memo_it
        self.title_id = title_id
        self.memo_id = memo_id
        self.title_th = title_th
        self.memo_th = memo_th
        self.title_pt = title_pt
        self.memo_pt = memo_pt
        self.title_hi = title_hi
        self.memo_hi = memo_hi
        self.have_reward = have_reward
        self.status = status
        self.unlimit_flg = unlimit_flg
        self.flg = flg
        self.create_time = create_time
        self.del_time = del_time
        self.item_list = item_list
        self.url = url
        self.image_resource_name = image_resource_name

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.idx = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I16:
                    self.notice_type = iprot.readI16()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.title_ko = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRING:
                    self.memo_ko = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.STRING:
                    self.title_en = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.STRING:
                    self.memo_en = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 7:
                if ftype == TType.STRING:
                    self.title_jp = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 8:
                if ftype == TType.STRING:
                    self.memo_jp = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 9:
                if ftype == TType.STRING:
                    self.title_zh_chs = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 10:
                if ftype == TType.STRING:
                    self.memo_zh_chs = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 11:
                if ftype == TType.STRING:
                    self.title_zh_cht = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 12:
                if ftype == TType.STRING:
                    self.memo_zh_cht = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 13:
                if ftype == TType.STRING:
                    self.title_vi = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 14:
                if ftype == TType.STRING:
                    self.memo_vi = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 15:
                if ftype == TType.STRING:
                    self.title_es = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 16:
                if ftype == TType.STRING:
                    self.memo_es = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 17:
                if ftype == TType.STRING:
                    self.title_it = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 18:
                if ftype == TType.STRING:
                    self.memo_it = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 19:
                if ftype == TType.STRING:
                    self.title_id = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 20:
                if ftype == TType.STRING:
                    self.memo_id = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 21:
                if ftype == TType.STRING:
                    self.title_th = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 22:
                if ftype == TType.STRING:
                    self.memo_th = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 23:
                if ftype == TType.STRING:
                    self.title_pt = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 24:
                if ftype == TType.STRING:
                    self.memo_pt = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 25:
                if ftype == TType.STRING:
                    self.title_hi = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 26:
                if ftype == TType.STRING:
                    self.memo_hi = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 27:
                if ftype == TType.I16:
                    self.have_reward = iprot.readI16()
                else:
                    iprot.skip(ftype)
            elif fid == 28:
                if ftype == TType.I16:
                    self.status = iprot.readI16()
                else:
                    iprot.skip(ftype)
            elif fid == 29:
                if ftype == TType.I16:
                    self.unlimit_flg = iprot.readI16()
                else:
                    iprot.skip(ftype)
            elif fid == 30:
                if ftype == TType.I16:
                    self.flg = iprot.readI16()
                else:
                    iprot.skip(ftype)
            elif fid == 31:
                if ftype == TType.I64:
                    self.create_time = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 32:
                if ftype == TType.I64:
                    self.del_time = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 33:
                if ftype == TType.LIST:
                    self.item_list = []
                    (_etype3, _size0) = iprot.readListBegin()
                    for _i4 in range(_size0):
                        _elem5 = itemList()
                        _elem5.read(iprot)
                        self.item_list.append(_elem5)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 34:
                if ftype == TType.STRING:
                    self.url = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 35:
                if ftype == TType.STRING:
                    self.image_resource_name = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('getPostList')
        if self.idx is not None:
            oprot.writeFieldBegin('idx', TType.I64, 1)
            oprot.writeI64(self.idx)
            oprot.writeFieldEnd()
        if self.notice_type is not None:
            oprot.writeFieldBegin('notice_type', TType.I16, 2)
            oprot.writeI16(self.notice_type)
            oprot.writeFieldEnd()
        if self.title_ko is not None:
            oprot.writeFieldBegin('title_ko', TType.STRING, 3)
            oprot.writeString(self.title_ko.encode('utf-8') if sys.version_info[0] == 2 else self.title_ko)
            oprot.writeFieldEnd()
        if self.memo_ko is not None:
            oprot.writeFieldBegin('memo_ko', TType.STRING, 4)
            oprot.writeString(self.memo_ko.encode('utf-8') if sys.version_info[0] == 2 else self.memo_ko)
            oprot.writeFieldEnd()
        if self.title_en is not None:
            oprot.writeFieldBegin('title_en', TType.STRING, 5)
            oprot.writeString(self.title_en.encode('utf-8') if sys.version_info[0] == 2 else self.title_en)
            oprot.writeFieldEnd()
        if self.memo_en is not None:
            oprot.writeFieldBegin('memo_en', TType.STRING, 6)
            oprot.writeString(self.memo_en.encode('utf-8') if sys.version_info[0] == 2 else self.memo_en)
            oprot.writeFieldEnd()
        if self.title_jp is not None:
            oprot.writeFieldBegin('title_jp', TType.STRING, 7)
            oprot.writeString(self.title_jp.encode('utf-8') if sys.version_info[0] == 2 else self.title_jp)
            oprot.writeFieldEnd()
        if self.memo_jp is not None:
            oprot.writeFieldBegin('memo_jp', TType.STRING, 8)
            oprot.writeString(self.memo_jp.encode('utf-8') if sys.version_info[0] == 2 else self.memo_jp)
            oprot.writeFieldEnd()
        if self.title_zh_chs is not None:
            oprot.writeFieldBegin('title_zh_chs', TType.STRING, 9)
            oprot.writeString(self.title_zh_chs.encode('utf-8') if sys.version_info[0] == 2 else self.title_zh_chs)
            oprot.writeFieldEnd()
        if self.memo_zh_chs is not None:
            oprot.writeFieldBegin('memo_zh_chs', TType.STRING, 10)
            oprot.writeString(self.memo_zh_chs.encode('utf-8') if sys.version_info[0] == 2 else self.memo_zh_chs)
            oprot.writeFieldEnd()
        if self.title_zh_cht is not None:
            oprot.writeFieldBegin('title_zh_cht', TType.STRING, 11)
            oprot.writeString(self.title_zh_cht.encode('utf-8') if sys.version_info[0] == 2 else self.title_zh_cht)
            oprot.writeFieldEnd()
        if self.memo_zh_cht is not None:
            oprot.writeFieldBegin('memo_zh_cht', TType.STRING, 12)
            oprot.writeString(self.memo_zh_cht.encode('utf-8') if sys.version_info[0] == 2 else self.memo_zh_cht)
            oprot.writeFieldEnd()
        if self.title_vi is not None:
            oprot.writeFieldBegin('title_vi', TType.STRING, 13)
            oprot.writeString(self.title_vi.encode('utf-8') if sys.version_info[0] == 2 else self.title_vi)
            oprot.writeFieldEnd()
        if self.memo_vi is not None:
            oprot.writeFieldBegin('memo_vi', TType.STRING, 14)
            oprot.writeString(self.memo_vi.encode('utf-8') if sys.version_info[0] == 2 else self.memo_vi)
            oprot.writeFieldEnd()
        if self.title_es is not None:
            oprot.writeFieldBegin('title_es', TType.STRING, 15)
            oprot.writeString(self.title_es.encode('utf-8') if sys.version_info[0] == 2 else self.title_es)
            oprot.writeFieldEnd()
        if self.memo_es is not None:
            oprot.writeFieldBegin('memo_es', TType.STRING, 16)
            oprot.writeString(self.memo_es.encode('utf-8') if sys.version_info[0] == 2 else self.memo_es)
            oprot.writeFieldEnd()
        if self.title_it is not None:
            oprot.writeFieldBegin('title_it', TType.STRING, 17)
            oprot.writeString(self.title_it.encode('utf-8') if sys.version_info[0] == 2 else self.title_it)
            oprot.writeFieldEnd()
        if self.memo_it is not None:
            oprot.writeFieldBegin('memo_it', TType.STRING, 18)
            oprot.writeString(self.memo_it.encode('utf-8') if sys.version_info[0] == 2 else self.memo_it)
            oprot.writeFieldEnd()
        if self.title_id is not None:
            oprot.writeFieldBegin('title_id', TType.STRING, 19)
            oprot.writeString(self.title_id.encode('utf-8') if sys.version_info[0] == 2 else self.title_id)
            oprot.writeFieldEnd()
        if self.memo_id is not None:
            oprot.writeFieldBegin('memo_id', TType.STRING, 20)
            oprot.writeString(self.memo_id.encode('utf-8') if sys.version_info[0] == 2 else self.memo_id)
            oprot.writeFieldEnd()
        if self.title_th is not None:
            oprot.writeFieldBegin('title_th', TType.STRING, 21)
            oprot.writeString(self.title_th.encode('utf-8') if sys.version_info[0] == 2 else self.title_th)
            oprot.writeFieldEnd()
        if self.memo_th is not None:
            oprot.writeFieldBegin('memo_th', TType.STRING, 22)
            oprot.writeString(self.memo_th.encode('utf-8') if sys.version_info[0] == 2 else self.memo_th)
            oprot.writeFieldEnd()
        if self.title_pt is not None:
            oprot.writeFieldBegin('title_pt', TType.STRING, 23)
            oprot.writeString(self.title_pt.encode('utf-8') if sys.version_info[0] == 2 else self.title_pt)
            oprot.writeFieldEnd()
        if self.memo_pt is not None:
            oprot.writeFieldBegin('memo_pt', TType.STRING, 24)
            oprot.writeString(self.memo_pt.encode('utf-8') if sys.version_info[0] == 2 else self.memo_pt)
            oprot.writeFieldEnd()
        if self.title_hi is not None:
            oprot.writeFieldBegin('title_hi', TType.STRING, 25)
            oprot.writeString(self.title_hi.encode('utf-8') if sys.version_info[0] == 2 else self.title_hi)
            oprot.writeFieldEnd()
        if self.memo_hi is not None:
            oprot.writeFieldBegin('memo_hi', TType.STRING, 26)
            oprot.writeString(self.memo_hi.encode('utf-8') if sys.version_info[0] == 2 else self.memo_hi)
            oprot.writeFieldEnd()
        if self.have_reward is not None:
            oprot.writeFieldBegin('have_reward', TType.I16, 27)
            oprot.writeI16(self.have_reward)
            oprot.writeFieldEnd()
        if self.status is not None:
            oprot.writeFieldBegin('status', TType.I16, 28)
            oprot.writeI16(self.status)
            oprot.writeFieldEnd()
        if self.unlimit_flg is not None:
            oprot.writeFieldBegin('unlimit_flg', TType.I16, 29)
            oprot.writeI16(self.unlimit_flg)
            oprot.writeFieldEnd()
        if self.flg is not None:
            oprot.writeFieldBegin('flg', TType.I16, 30)
            oprot.writeI16(self.flg)
            oprot.writeFieldEnd()
        if self.create_time is not None:
            oprot.writeFieldBegin('create_time', TType.I64, 31)
            oprot.writeI64(self.create_time)
            oprot.writeFieldEnd()
        if self.del_time is not None:
            oprot.writeFieldBegin('del_time', TType.I64, 32)
            oprot.writeI64(self.del_time)
            oprot.writeFieldEnd()
        if self.item_list is not None:
            oprot.writeFieldBegin('item_list', TType.LIST, 33)
            oprot.writeListBegin(TType.STRUCT, len(self.item_list))
            for iter6 in self.item_list:
                iter6.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.url is not None:
            oprot.writeFieldBegin('url', TType.STRING, 34)
            oprot.writeString(self.url.encode('utf-8') if sys.version_info[0] == 2 else self.url)
            oprot.writeFieldEnd()
        if self.image_resource_name is not None:
            oprot.writeFieldBegin('image_resource_name', TType.STRING, 35)
            oprot.writeString(self.image_resource_name.encode('utf-8') if sys.version_info[0] == 2 else self.image_resource_name)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class getPostRetDataInfo(object):
    """
    Attributes:
     - server_time
     - post_list

    """
    thrift_spec = None


    def __init__(self, server_time = None, post_list = None,):
        self.server_time = server_time
        self.post_list = post_list

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.server_time = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.LIST:
                    self.post_list = []
                    (_etype10, _size7) = iprot.readListBegin()
                    for _i11 in range(_size7):
                        _elem12 = getPostList()
                        _elem12.read(iprot)
                        self.post_list.append(_elem12)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('getPostRetDataInfo')
        if self.server_time is not None:
            oprot.writeFieldBegin('server_time', TType.I64, 1)
            oprot.writeI64(self.server_time)
            oprot.writeFieldEnd()
        if self.post_list is not None:
            oprot.writeFieldBegin('post_list', TType.LIST, 2)
            oprot.writeListBegin(TType.STRUCT, len(self.post_list))
            for iter13 in self.post_list:
                iter13.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class getPostReturn(object):
    """
    Attributes:
     - error
     - server_time
     - mode
     - call
     - data
     - maintenance

    """
    thrift_spec = None


    def __init__(self, error = None, server_time = None, mode = None, call = None, data = None, maintenance = None,):
        self.error = error
        self.server_time = server_time
        self.mode = mode
        self.call = call
        self.data = data
        self.maintenance = maintenance

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.error = tapsonic.common.ttypes.errorRetCode()
                    self.error.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.server_time = tapsonic.common.ttypes.serverTimeRet()
                    self.server_time.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.mode = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRING:
                    self.call = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.STRUCT:
                    self.data = getPostRetDataInfo()
                    self.data.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.STRUCT:
                    self.maintenance = tapsonic.common.ttypes.maintenanceData()
                    self.maintenance.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('getPostReturn')
        if self.error is not None:
            oprot.writeFieldBegin('error', TType.STRUCT, 1)
            self.error.write(oprot)
            oprot.writeFieldEnd()
        if self.server_time is not None:
            oprot.writeFieldBegin('server_time', TType.STRUCT, 2)
            self.server_time.write(oprot)
            oprot.writeFieldEnd()
        if self.mode is not None:
            oprot.writeFieldBegin('mode', TType.STRING, 3)
            oprot.writeString(self.mode.encode('utf-8') if sys.version_info[0] == 2 else self.mode)
            oprot.writeFieldEnd()
        if self.call is not None:
            oprot.writeFieldBegin('call', TType.STRING, 4)
            oprot.writeString(self.call.encode('utf-8') if sys.version_info[0] == 2 else self.call)
            oprot.writeFieldEnd()
        if self.data is not None:
            oprot.writeFieldBegin('data', TType.STRUCT, 5)
            self.data.write(oprot)
            oprot.writeFieldEnd()
        if self.maintenance is not None:
            oprot.writeFieldBegin('maintenance', TType.STRUCT, 6)
            self.maintenance.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(getPostDataInfo)
getPostDataInfo.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'u_seq', None, None, ),  # 1
    (2, TType.STRING, 'u_id', 'UTF8', None, ),  # 2
    (3, TType.STRING, 'uuid', 'UTF8', None, ),  # 3
    (4, TType.STRING, 'device_uuid', 'UTF8', None, ),  # 4
)
all_structs.append(getPost)
getPost.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'call', 'UTF8', None, ),  # 1
    (2, TType.STRUCT, 'data', [getPostDataInfo, None], None, ),  # 2
    (3, TType.STRUCT, 'common_data', [tapsonic.common.ttypes.paramData, None], None, ),  # 3
)
all_structs.append(itemList)
itemList.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'i_RewardType', None, None, ),  # 1
    (2, TType.I32, 'i_RewardId', None, None, ),  # 2
    (3, TType.DOUBLE, 'd_RewardQuantity', None, None, ),  # 3
)
all_structs.append(getPostList)
getPostList.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'idx', None, None, ),  # 1
    (2, TType.I16, 'notice_type', None, None, ),  # 2
    (3, TType.STRING, 'title_ko', 'UTF8', None, ),  # 3
    (4, TType.STRING, 'memo_ko', 'UTF8', None, ),  # 4
    (5, TType.STRING, 'title_en', 'UTF8', None, ),  # 5
    (6, TType.STRING, 'memo_en', 'UTF8', None, ),  # 6
    (7, TType.STRING, 'title_jp', 'UTF8', None, ),  # 7
    (8, TType.STRING, 'memo_jp', 'UTF8', None, ),  # 8
    (9, TType.STRING, 'title_zh_chs', 'UTF8', None, ),  # 9
    (10, TType.STRING, 'memo_zh_chs', 'UTF8', None, ),  # 10
    (11, TType.STRING, 'title_zh_cht', 'UTF8', None, ),  # 11
    (12, TType.STRING, 'memo_zh_cht', 'UTF8', None, ),  # 12
    (13, TType.STRING, 'title_vi', 'UTF8', None, ),  # 13
    (14, TType.STRING, 'memo_vi', 'UTF8', None, ),  # 14
    (15, TType.STRING, 'title_es', 'UTF8', None, ),  # 15
    (16, TType.STRING, 'memo_es', 'UTF8', None, ),  # 16
    (17, TType.STRING, 'title_it', 'UTF8', None, ),  # 17
    (18, TType.STRING, 'memo_it', 'UTF8', None, ),  # 18
    (19, TType.STRING, 'title_id', 'UTF8', None, ),  # 19
    (20, TType.STRING, 'memo_id', 'UTF8', None, ),  # 20
    (21, TType.STRING, 'title_th', 'UTF8', None, ),  # 21
    (22, TType.STRING, 'memo_th', 'UTF8', None, ),  # 22
    (23, TType.STRING, 'title_pt', 'UTF8', None, ),  # 23
    (24, TType.STRING, 'memo_pt', 'UTF8', None, ),  # 24
    (25, TType.STRING, 'title_hi', 'UTF8', None, ),  # 25
    (26, TType.STRING, 'memo_hi', 'UTF8', None, ),  # 26
    (27, TType.I16, 'have_reward', None, None, ),  # 27
    (28, TType.I16, 'status', None, None, ),  # 28
    (29, TType.I16, 'unlimit_flg', None, None, ),  # 29
    (30, TType.I16, 'flg', None, None, ),  # 30
    (31, TType.I64, 'create_time', None, None, ),  # 31
    (32, TType.I64, 'del_time', None, None, ),  # 32
    (33, TType.LIST, 'item_list', (TType.STRUCT, [itemList, None], False), None, ),  # 33
    (34, TType.STRING, 'url', 'UTF8', None, ),  # 34
    (35, TType.STRING, 'image_resource_name', 'UTF8', None, ),  # 35
)
all_structs.append(getPostRetDataInfo)
getPostRetDataInfo.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'server_time', None, None, ),  # 1
    (2, TType.LIST, 'post_list', (TType.STRUCT, [getPostList, None], False), None, ),  # 2
)
all_structs.append(getPostReturn)
getPostReturn.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'error', [tapsonic.common.ttypes.errorRetCode, None], None, ),  # 1
    (2, TType.STRUCT, 'server_time', [tapsonic.common.ttypes.serverTimeRet, None], None, ),  # 2
    (3, TType.STRING, 'mode', 'UTF8', None, ),  # 3
    (4, TType.STRING, 'call', 'UTF8', None, ),  # 4
    (5, TType.STRUCT, 'data', [getPostRetDataInfo, None], None, ),  # 5
    (6, TType.STRUCT, 'maintenance', [tapsonic.common.ttypes.maintenanceData, None], None, ),  # 6
)
fix_spec(all_structs)
del all_structs
