#
# Autogenerated by Thrift Compiler (0.22.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec
from uuid import UUID

import sys
import tapsonic.general.ttypes

from thrift.transport import TTransport
all_structs = []


class saveUserInfo(object):
    """
    Attributes:
     - u_like
     - u_fans
     - u_fans_grade
     - u_selected_costume_id
     - u_selected_music_id

    """
    thrift_spec = None


    def __init__(self, u_like = None, u_fans = None, u_fans_grade = None, u_selected_costume_id = None, u_selected_music_id = None,):
        self.u_like = u_like
        self.u_fans = u_fans
        self.u_fans_grade = u_fans_grade
        self.u_selected_costume_id = u_selected_costume_id
        self.u_selected_music_id = u_selected_music_id

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.DOUBLE:
                    self.u_like = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I64:
                    self.u_fans = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I16:
                    self.u_fans_grade = iprot.readI16()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I64:
                    self.u_selected_costume_id = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.I64:
                    self.u_selected_music_id = iprot.readI64()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('saveUserInfo')
        if self.u_like is not None:
            oprot.writeFieldBegin('u_like', TType.DOUBLE, 1)
            oprot.writeDouble(self.u_like)
            oprot.writeFieldEnd()
        if self.u_fans is not None:
            oprot.writeFieldBegin('u_fans', TType.I64, 2)
            oprot.writeI64(self.u_fans)
            oprot.writeFieldEnd()
        if self.u_fans_grade is not None:
            oprot.writeFieldBegin('u_fans_grade', TType.I16, 3)
            oprot.writeI16(self.u_fans_grade)
            oprot.writeFieldEnd()
        if self.u_selected_costume_id is not None:
            oprot.writeFieldBegin('u_selected_costume_id', TType.I64, 4)
            oprot.writeI64(self.u_selected_costume_id)
            oprot.writeFieldEnd()
        if self.u_selected_music_id is not None:
            oprot.writeFieldBegin('u_selected_music_id', TType.I64, 5)
            oprot.writeI64(self.u_selected_music_id)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class saveUserAreaInfo(object):
    """
    Attributes:
     - u_area_num
     - d_Like
     - i_UserFanCount
     - i_UserFanGrade
     - i_SelectedCostumeId
     - i_SelectedMusicId
     - i_SelectedGuitarId
     - d_Candy
     - s_TutorialList
     - s_Gp1
     - s_Gp2

    """
    thrift_spec = None


    def __init__(self, u_area_num = None, d_Like = None, i_UserFanCount = None, i_UserFanGrade = None, i_SelectedCostumeId = None, i_SelectedMusicId = None, i_SelectedGuitarId = None, d_Candy = None, s_TutorialList = None, s_Gp1 = None, s_Gp2 = None,):
        self.u_area_num = u_area_num
        self.d_Like = d_Like
        self.i_UserFanCount = i_UserFanCount
        self.i_UserFanGrade = i_UserFanGrade
        self.i_SelectedCostumeId = i_SelectedCostumeId
        self.i_SelectedMusicId = i_SelectedMusicId
        self.i_SelectedGuitarId = i_SelectedGuitarId
        self.d_Candy = d_Candy
        self.s_TutorialList = s_TutorialList
        self.s_Gp1 = s_Gp1
        self.s_Gp2 = s_Gp2

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I16:
                    self.u_area_num = iprot.readI16()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.DOUBLE:
                    self.d_Like = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I64:
                    self.i_UserFanCount = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I16:
                    self.i_UserFanGrade = iprot.readI16()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.I64:
                    self.i_SelectedCostumeId = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.I64:
                    self.i_SelectedMusicId = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 7:
                if ftype == TType.I64:
                    self.i_SelectedGuitarId = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 8:
                if ftype == TType.DOUBLE:
                    self.d_Candy = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 9:
                if ftype == TType.STRING:
                    self.s_TutorialList = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 10:
                if ftype == TType.STRING:
                    self.s_Gp1 = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 11:
                if ftype == TType.STRING:
                    self.s_Gp2 = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('saveUserAreaInfo')
        if self.u_area_num is not None:
            oprot.writeFieldBegin('u_area_num', TType.I16, 1)
            oprot.writeI16(self.u_area_num)
            oprot.writeFieldEnd()
        if self.d_Like is not None:
            oprot.writeFieldBegin('d_Like', TType.DOUBLE, 2)
            oprot.writeDouble(self.d_Like)
            oprot.writeFieldEnd()
        if self.i_UserFanCount is not None:
            oprot.writeFieldBegin('i_UserFanCount', TType.I64, 3)
            oprot.writeI64(self.i_UserFanCount)
            oprot.writeFieldEnd()
        if self.i_UserFanGrade is not None:
            oprot.writeFieldBegin('i_UserFanGrade', TType.I16, 4)
            oprot.writeI16(self.i_UserFanGrade)
            oprot.writeFieldEnd()
        if self.i_SelectedCostumeId is not None:
            oprot.writeFieldBegin('i_SelectedCostumeId', TType.I64, 5)
            oprot.writeI64(self.i_SelectedCostumeId)
            oprot.writeFieldEnd()
        if self.i_SelectedMusicId is not None:
            oprot.writeFieldBegin('i_SelectedMusicId', TType.I64, 6)
            oprot.writeI64(self.i_SelectedMusicId)
            oprot.writeFieldEnd()
        if self.i_SelectedGuitarId is not None:
            oprot.writeFieldBegin('i_SelectedGuitarId', TType.I64, 7)
            oprot.writeI64(self.i_SelectedGuitarId)
            oprot.writeFieldEnd()
        if self.d_Candy is not None:
            oprot.writeFieldBegin('d_Candy', TType.DOUBLE, 8)
            oprot.writeDouble(self.d_Candy)
            oprot.writeFieldEnd()
        if self.s_TutorialList is not None:
            oprot.writeFieldBegin('s_TutorialList', TType.STRING, 9)
            oprot.writeString(self.s_TutorialList.encode('utf-8') if sys.version_info[0] == 2 else self.s_TutorialList)
            oprot.writeFieldEnd()
        if self.s_Gp1 is not None:
            oprot.writeFieldBegin('s_Gp1', TType.STRING, 10)
            oprot.writeString(self.s_Gp1.encode('utf-8') if sys.version_info[0] == 2 else self.s_Gp1)
            oprot.writeFieldEnd()
        if self.s_Gp2 is not None:
            oprot.writeFieldBegin('s_Gp2', TType.STRING, 11)
            oprot.writeString(self.s_Gp2.encode('utf-8') if sys.version_info[0] == 2 else self.s_Gp2)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class saveUserAchievement(object):
    """
    Attributes:
     - i_id
     - d_Quantity
     - s_Quantity

    """
    thrift_spec = None


    def __init__(self, i_id = None, d_Quantity = None, s_Quantity = None,):
        self.i_id = i_id
        self.d_Quantity = d_Quantity
        self.s_Quantity = s_Quantity

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.i_id = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.DOUBLE:
                    self.d_Quantity = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.s_Quantity = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('saveUserAchievement')
        if self.i_id is not None:
            oprot.writeFieldBegin('i_id', TType.I64, 1)
            oprot.writeI64(self.i_id)
            oprot.writeFieldEnd()
        if self.d_Quantity is not None:
            oprot.writeFieldBegin('d_Quantity', TType.DOUBLE, 2)
            oprot.writeDouble(self.d_Quantity)
            oprot.writeFieldEnd()
        if self.s_Quantity is not None:
            oprot.writeFieldBegin('s_Quantity', TType.STRING, 3)
            oprot.writeString(self.s_Quantity.encode('utf-8') if sys.version_info[0] == 2 else self.s_Quantity)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class saveUserCharacter(object):
    """
    Attributes:
     - i_id
     - i_Level
     - i_BonusLevel

    """
    thrift_spec = None


    def __init__(self, i_id = None, i_Level = None, i_BonusLevel = None,):
        self.i_id = i_id
        self.i_Level = i_Level
        self.i_BonusLevel = i_BonusLevel

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.i_id = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I64:
                    self.i_Level = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I64:
                    self.i_BonusLevel = iprot.readI64()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('saveUserCharacter')
        if self.i_id is not None:
            oprot.writeFieldBegin('i_id', TType.I64, 1)
            oprot.writeI64(self.i_id)
            oprot.writeFieldEnd()
        if self.i_Level is not None:
            oprot.writeFieldBegin('i_Level', TType.I64, 2)
            oprot.writeI64(self.i_Level)
            oprot.writeFieldEnd()
        if self.i_BonusLevel is not None:
            oprot.writeFieldBegin('i_BonusLevel', TType.I64, 3)
            oprot.writeI64(self.i_BonusLevel)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class saveUserCostume(object):
    """
    Attributes:
     - i_id
     - i_Level
     - i_BonusLevel

    """
    thrift_spec = None


    def __init__(self, i_id = None, i_Level = None, i_BonusLevel = None,):
        self.i_id = i_id
        self.i_Level = i_Level
        self.i_BonusLevel = i_BonusLevel

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.i_id = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I64:
                    self.i_Level = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I64:
                    self.i_BonusLevel = iprot.readI64()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('saveUserCostume')
        if self.i_id is not None:
            oprot.writeFieldBegin('i_id', TType.I64, 1)
            oprot.writeI64(self.i_id)
            oprot.writeFieldEnd()
        if self.i_Level is not None:
            oprot.writeFieldBegin('i_Level', TType.I64, 2)
            oprot.writeI64(self.i_Level)
            oprot.writeFieldEnd()
        if self.i_BonusLevel is not None:
            oprot.writeFieldBegin('i_BonusLevel', TType.I64, 3)
            oprot.writeI64(self.i_BonusLevel)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class saveUserDailyMission(object):
    """
    Attributes:
     - i_id
     - d_Quantity

    """
    thrift_spec = None


    def __init__(self, i_id = None, d_Quantity = None,):
        self.i_id = i_id
        self.d_Quantity = d_Quantity

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.i_id = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I64:
                    self.d_Quantity = iprot.readI64()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('saveUserDailyMission')
        if self.i_id is not None:
            oprot.writeFieldBegin('i_id', TType.I64, 1)
            oprot.writeI64(self.i_id)
            oprot.writeFieldEnd()
        if self.d_Quantity is not None:
            oprot.writeFieldBegin('d_Quantity', TType.I64, 2)
            oprot.writeI64(self.d_Quantity)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class saveUserFollower(object):
    """
    Attributes:
     - i_id
     - i_Level
     - i_BonusLevel

    """
    thrift_spec = None


    def __init__(self, i_id = None, i_Level = None, i_BonusLevel = None,):
        self.i_id = i_id
        self.i_Level = i_Level
        self.i_BonusLevel = i_BonusLevel

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.i_id = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I64:
                    self.i_Level = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I64:
                    self.i_BonusLevel = iprot.readI64()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('saveUserFollower')
        if self.i_id is not None:
            oprot.writeFieldBegin('i_id', TType.I64, 1)
            oprot.writeI64(self.i_id)
            oprot.writeFieldEnd()
        if self.i_Level is not None:
            oprot.writeFieldBegin('i_Level', TType.I64, 2)
            oprot.writeI64(self.i_Level)
            oprot.writeFieldEnd()
        if self.i_BonusLevel is not None:
            oprot.writeFieldBegin('i_BonusLevel', TType.I64, 3)
            oprot.writeI64(self.i_BonusLevel)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class saveUserMusic(object):
    """
    Attributes:
     - i_id
     - i_Level
     - i_BonusLevel
     - b_EncoreBonusAppear
     - i_EncoreBonusFollowerId

    """
    thrift_spec = None


    def __init__(self, i_id = None, i_Level = None, i_BonusLevel = None, b_EncoreBonusAppear = None, i_EncoreBonusFollowerId = None,):
        self.i_id = i_id
        self.i_Level = i_Level
        self.i_BonusLevel = i_BonusLevel
        self.b_EncoreBonusAppear = b_EncoreBonusAppear
        self.i_EncoreBonusFollowerId = i_EncoreBonusFollowerId

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.i_id = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I64:
                    self.i_Level = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I64:
                    self.i_BonusLevel = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I64:
                    self.b_EncoreBonusAppear = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.I64:
                    self.i_EncoreBonusFollowerId = iprot.readI64()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('saveUserMusic')
        if self.i_id is not None:
            oprot.writeFieldBegin('i_id', TType.I64, 1)
            oprot.writeI64(self.i_id)
            oprot.writeFieldEnd()
        if self.i_Level is not None:
            oprot.writeFieldBegin('i_Level', TType.I64, 2)
            oprot.writeI64(self.i_Level)
            oprot.writeFieldEnd()
        if self.i_BonusLevel is not None:
            oprot.writeFieldBegin('i_BonusLevel', TType.I64, 3)
            oprot.writeI64(self.i_BonusLevel)
            oprot.writeFieldEnd()
        if self.b_EncoreBonusAppear is not None:
            oprot.writeFieldBegin('b_EncoreBonusAppear', TType.I64, 4)
            oprot.writeI64(self.b_EncoreBonusAppear)
            oprot.writeFieldEnd()
        if self.i_EncoreBonusFollowerId is not None:
            oprot.writeFieldBegin('i_EncoreBonusFollowerId', TType.I64, 5)
            oprot.writeI64(self.i_EncoreBonusFollowerId)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class saveUserSkill(object):
    """
    Attributes:
     - i_id
     - b_Activate
     - l_ActivateOnTicks
     - l_ActivateOffTicks

    """
    thrift_spec = None


    def __init__(self, i_id = None, b_Activate = None, l_ActivateOnTicks = None, l_ActivateOffTicks = None,):
        self.i_id = i_id
        self.b_Activate = b_Activate
        self.l_ActivateOnTicks = l_ActivateOnTicks
        self.l_ActivateOffTicks = l_ActivateOffTicks

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.i_id = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I16:
                    self.b_Activate = iprot.readI16()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I64:
                    self.l_ActivateOnTicks = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I64:
                    self.l_ActivateOffTicks = iprot.readI64()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('saveUserSkill')
        if self.i_id is not None:
            oprot.writeFieldBegin('i_id', TType.I64, 1)
            oprot.writeI64(self.i_id)
            oprot.writeFieldEnd()
        if self.b_Activate is not None:
            oprot.writeFieldBegin('b_Activate', TType.I16, 2)
            oprot.writeI16(self.b_Activate)
            oprot.writeFieldEnd()
        if self.l_ActivateOnTicks is not None:
            oprot.writeFieldBegin('l_ActivateOnTicks', TType.I64, 3)
            oprot.writeI64(self.l_ActivateOnTicks)
            oprot.writeFieldEnd()
        if self.l_ActivateOffTicks is not None:
            oprot.writeFieldBegin('l_ActivateOffTicks', TType.I64, 4)
            oprot.writeI64(self.l_ActivateOffTicks)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class saveUserMessenger(object):
    """
    Attributes:
     - i_MessengerChatRoomId
     - i_LastConfirmIndex
     - s_UnlockGroupList
     - l_UpdateTimeTicks

    """
    thrift_spec = None


    def __init__(self, i_MessengerChatRoomId = None, i_LastConfirmIndex = None, s_UnlockGroupList = None, l_UpdateTimeTicks = None,):
        self.i_MessengerChatRoomId = i_MessengerChatRoomId
        self.i_LastConfirmIndex = i_LastConfirmIndex
        self.s_UnlockGroupList = s_UnlockGroupList
        self.l_UpdateTimeTicks = l_UpdateTimeTicks

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.i_MessengerChatRoomId = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I64:
                    self.i_LastConfirmIndex = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.s_UnlockGroupList = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I64:
                    self.l_UpdateTimeTicks = iprot.readI64()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('saveUserMessenger')
        if self.i_MessengerChatRoomId is not None:
            oprot.writeFieldBegin('i_MessengerChatRoomId', TType.I64, 1)
            oprot.writeI64(self.i_MessengerChatRoomId)
            oprot.writeFieldEnd()
        if self.i_LastConfirmIndex is not None:
            oprot.writeFieldBegin('i_LastConfirmIndex', TType.I64, 2)
            oprot.writeI64(self.i_LastConfirmIndex)
            oprot.writeFieldEnd()
        if self.s_UnlockGroupList is not None:
            oprot.writeFieldBegin('s_UnlockGroupList', TType.STRING, 3)
            oprot.writeString(self.s_UnlockGroupList.encode('utf-8') if sys.version_info[0] == 2 else self.s_UnlockGroupList)
            oprot.writeFieldEnd()
        if self.l_UpdateTimeTicks is not None:
            oprot.writeFieldBegin('l_UpdateTimeTicks', TType.I64, 4)
            oprot.writeI64(self.l_UpdateTimeTicks)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class saveUserGuitar(object):
    """
    Attributes:
     - i_id
     - i_Level
     - i_BonusLevel

    """
    thrift_spec = None


    def __init__(self, i_id = None, i_Level = None, i_BonusLevel = None,):
        self.i_id = i_id
        self.i_Level = i_Level
        self.i_BonusLevel = i_BonusLevel

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.i_id = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I64:
                    self.i_Level = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I64:
                    self.i_BonusLevel = iprot.readI64()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('saveUserGuitar')
        if self.i_id is not None:
            oprot.writeFieldBegin('i_id', TType.I64, 1)
            oprot.writeI64(self.i_id)
            oprot.writeFieldEnd()
        if self.i_Level is not None:
            oprot.writeFieldBegin('i_Level', TType.I64, 2)
            oprot.writeI64(self.i_Level)
            oprot.writeFieldEnd()
        if self.i_BonusLevel is not None:
            oprot.writeFieldBegin('i_BonusLevel', TType.I64, 3)
            oprot.writeI64(self.i_BonusLevel)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class saveUserEventPoint(object):
    """
    Attributes:
     - s_EventType
     - i_DataID
     - i_Point
     - i_Step
     - i_Version

    """
    thrift_spec = None


    def __init__(self, s_EventType = None, i_DataID = None, i_Point = None, i_Step = None, i_Version = None,):
        self.s_EventType = s_EventType
        self.i_DataID = i_DataID
        self.i_Point = i_Point
        self.i_Step = i_Step
        self.i_Version = i_Version

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.s_EventType = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I64:
                    self.i_DataID = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I64:
                    self.i_Point = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I64:
                    self.i_Step = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.I32:
                    self.i_Version = iprot.readI32()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('saveUserEventPoint')
        if self.s_EventType is not None:
            oprot.writeFieldBegin('s_EventType', TType.STRING, 1)
            oprot.writeString(self.s_EventType.encode('utf-8') if sys.version_info[0] == 2 else self.s_EventType)
            oprot.writeFieldEnd()
        if self.i_DataID is not None:
            oprot.writeFieldBegin('i_DataID', TType.I64, 2)
            oprot.writeI64(self.i_DataID)
            oprot.writeFieldEnd()
        if self.i_Point is not None:
            oprot.writeFieldBegin('i_Point', TType.I64, 3)
            oprot.writeI64(self.i_Point)
            oprot.writeFieldEnd()
        if self.i_Step is not None:
            oprot.writeFieldBegin('i_Step', TType.I64, 4)
            oprot.writeI64(self.i_Step)
            oprot.writeFieldEnd()
        if self.i_Version is not None:
            oprot.writeFieldBegin('i_Version', TType.I32, 5)
            oprot.writeI32(self.i_Version)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class saveUserFollowerQuest(object):
    """
    Attributes:
     - i_CurrentID
     - d_ConditionValue1
     - d_ConditionValue2
     - d_ConditionValue3

    """
    thrift_spec = None


    def __init__(self, i_CurrentID = None, d_ConditionValue1 = None, d_ConditionValue2 = None, d_ConditionValue3 = None,):
        self.i_CurrentID = i_CurrentID
        self.d_ConditionValue1 = d_ConditionValue1
        self.d_ConditionValue2 = d_ConditionValue2
        self.d_ConditionValue3 = d_ConditionValue3

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.i_CurrentID = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.DOUBLE:
                    self.d_ConditionValue1 = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.DOUBLE:
                    self.d_ConditionValue2 = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.DOUBLE:
                    self.d_ConditionValue3 = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('saveUserFollowerQuest')
        if self.i_CurrentID is not None:
            oprot.writeFieldBegin('i_CurrentID', TType.I32, 1)
            oprot.writeI32(self.i_CurrentID)
            oprot.writeFieldEnd()
        if self.d_ConditionValue1 is not None:
            oprot.writeFieldBegin('d_ConditionValue1', TType.DOUBLE, 2)
            oprot.writeDouble(self.d_ConditionValue1)
            oprot.writeFieldEnd()
        if self.d_ConditionValue2 is not None:
            oprot.writeFieldBegin('d_ConditionValue2', TType.DOUBLE, 3)
            oprot.writeDouble(self.d_ConditionValue2)
            oprot.writeFieldEnd()
        if self.d_ConditionValue3 is not None:
            oprot.writeFieldBegin('d_ConditionValue3', TType.DOUBLE, 4)
            oprot.writeDouble(self.d_ConditionValue3)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class userSaveDataInfo(object):
    """
    Attributes:
     - u_seq
     - u_id
     - uuid
     - device_uuid
     - type
     - user_info
     - user_area_info
     - user_achievement
     - user_character
     - user_costume
     - user_daily_mission
     - user_follower
     - user_music
     - user_skill
     - user_messenger
     - user_guitar
     - user_event_point
     - user_follower_quest

    """
    thrift_spec = None


    def __init__(self, u_seq = None, u_id = None, uuid = None, device_uuid = None, type = None, user_info = None, user_area_info = None, user_achievement = None, user_character = None, user_costume = None, user_daily_mission = None, user_follower = None, user_music = None, user_skill = None, user_messenger = None, user_guitar = None, user_event_point = None, user_follower_quest = None,):
        self.u_seq = u_seq
        self.u_id = u_id
        self.uuid = uuid
        self.device_uuid = device_uuid
        self.type = type
        self.user_info = user_info
        self.user_area_info = user_area_info
        self.user_achievement = user_achievement
        self.user_character = user_character
        self.user_costume = user_costume
        self.user_daily_mission = user_daily_mission
        self.user_follower = user_follower
        self.user_music = user_music
        self.user_skill = user_skill
        self.user_messenger = user_messenger
        self.user_guitar = user_guitar
        self.user_event_point = user_event_point
        self.user_follower_quest = user_follower_quest

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.u_seq = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRING:
                    self.u_id = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.uuid = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRING:
                    self.device_uuid = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.STRING:
                    self.type = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.LIST:
                    self.user_info = []
                    (_etype3, _size0) = iprot.readListBegin()
                    for _i4 in range(_size0):
                        _elem5 = saveUserInfo()
                        _elem5.read(iprot)
                        self.user_info.append(_elem5)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 7:
                if ftype == TType.LIST:
                    self.user_area_info = []
                    (_etype9, _size6) = iprot.readListBegin()
                    for _i10 in range(_size6):
                        _elem11 = saveUserAreaInfo()
                        _elem11.read(iprot)
                        self.user_area_info.append(_elem11)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 8:
                if ftype == TType.LIST:
                    self.user_achievement = []
                    (_etype15, _size12) = iprot.readListBegin()
                    for _i16 in range(_size12):
                        _elem17 = saveUserAchievement()
                        _elem17.read(iprot)
                        self.user_achievement.append(_elem17)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 9:
                if ftype == TType.LIST:
                    self.user_character = []
                    (_etype21, _size18) = iprot.readListBegin()
                    for _i22 in range(_size18):
                        _elem23 = saveUserCharacter()
                        _elem23.read(iprot)
                        self.user_character.append(_elem23)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 10:
                if ftype == TType.LIST:
                    self.user_costume = []
                    (_etype27, _size24) = iprot.readListBegin()
                    for _i28 in range(_size24):
                        _elem29 = saveUserCostume()
                        _elem29.read(iprot)
                        self.user_costume.append(_elem29)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 11:
                if ftype == TType.LIST:
                    self.user_daily_mission = []
                    (_etype33, _size30) = iprot.readListBegin()
                    for _i34 in range(_size30):
                        _elem35 = saveUserDailyMission()
                        _elem35.read(iprot)
                        self.user_daily_mission.append(_elem35)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 12:
                if ftype == TType.LIST:
                    self.user_follower = []
                    (_etype39, _size36) = iprot.readListBegin()
                    for _i40 in range(_size36):
                        _elem41 = saveUserFollower()
                        _elem41.read(iprot)
                        self.user_follower.append(_elem41)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 13:
                if ftype == TType.LIST:
                    self.user_music = []
                    (_etype45, _size42) = iprot.readListBegin()
                    for _i46 in range(_size42):
                        _elem47 = saveUserMusic()
                        _elem47.read(iprot)
                        self.user_music.append(_elem47)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 14:
                if ftype == TType.LIST:
                    self.user_skill = []
                    (_etype51, _size48) = iprot.readListBegin()
                    for _i52 in range(_size48):
                        _elem53 = saveUserSkill()
                        _elem53.read(iprot)
                        self.user_skill.append(_elem53)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 15:
                if ftype == TType.LIST:
                    self.user_messenger = []
                    (_etype57, _size54) = iprot.readListBegin()
                    for _i58 in range(_size54):
                        _elem59 = saveUserMessenger()
                        _elem59.read(iprot)
                        self.user_messenger.append(_elem59)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 16:
                if ftype == TType.LIST:
                    self.user_guitar = []
                    (_etype63, _size60) = iprot.readListBegin()
                    for _i64 in range(_size60):
                        _elem65 = saveUserGuitar()
                        _elem65.read(iprot)
                        self.user_guitar.append(_elem65)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 17:
                if ftype == TType.LIST:
                    self.user_event_point = []
                    (_etype69, _size66) = iprot.readListBegin()
                    for _i70 in range(_size66):
                        _elem71 = saveUserEventPoint()
                        _elem71.read(iprot)
                        self.user_event_point.append(_elem71)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 18:
                if ftype == TType.LIST:
                    self.user_follower_quest = []
                    (_etype75, _size72) = iprot.readListBegin()
                    for _i76 in range(_size72):
                        _elem77 = saveUserFollowerQuest()
                        _elem77.read(iprot)
                        self.user_follower_quest.append(_elem77)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('userSaveDataInfo')
        if self.u_seq is not None:
            oprot.writeFieldBegin('u_seq', TType.I32, 1)
            oprot.writeI32(self.u_seq)
            oprot.writeFieldEnd()
        if self.u_id is not None:
            oprot.writeFieldBegin('u_id', TType.STRING, 2)
            oprot.writeString(self.u_id.encode('utf-8') if sys.version_info[0] == 2 else self.u_id)
            oprot.writeFieldEnd()
        if self.uuid is not None:
            oprot.writeFieldBegin('uuid', TType.STRING, 3)
            oprot.writeString(self.uuid.encode('utf-8') if sys.version_info[0] == 2 else self.uuid)
            oprot.writeFieldEnd()
        if self.device_uuid is not None:
            oprot.writeFieldBegin('device_uuid', TType.STRING, 4)
            oprot.writeString(self.device_uuid.encode('utf-8') if sys.version_info[0] == 2 else self.device_uuid)
            oprot.writeFieldEnd()
        if self.type is not None:
            oprot.writeFieldBegin('type', TType.STRING, 5)
            oprot.writeString(self.type.encode('utf-8') if sys.version_info[0] == 2 else self.type)
            oprot.writeFieldEnd()
        if self.user_info is not None:
            oprot.writeFieldBegin('user_info', TType.LIST, 6)
            oprot.writeListBegin(TType.STRUCT, len(self.user_info))
            for iter78 in self.user_info:
                iter78.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.user_area_info is not None:
            oprot.writeFieldBegin('user_area_info', TType.LIST, 7)
            oprot.writeListBegin(TType.STRUCT, len(self.user_area_info))
            for iter79 in self.user_area_info:
                iter79.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.user_achievement is not None:
            oprot.writeFieldBegin('user_achievement', TType.LIST, 8)
            oprot.writeListBegin(TType.STRUCT, len(self.user_achievement))
            for iter80 in self.user_achievement:
                iter80.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.user_character is not None:
            oprot.writeFieldBegin('user_character', TType.LIST, 9)
            oprot.writeListBegin(TType.STRUCT, len(self.user_character))
            for iter81 in self.user_character:
                iter81.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.user_costume is not None:
            oprot.writeFieldBegin('user_costume', TType.LIST, 10)
            oprot.writeListBegin(TType.STRUCT, len(self.user_costume))
            for iter82 in self.user_costume:
                iter82.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.user_daily_mission is not None:
            oprot.writeFieldBegin('user_daily_mission', TType.LIST, 11)
            oprot.writeListBegin(TType.STRUCT, len(self.user_daily_mission))
            for iter83 in self.user_daily_mission:
                iter83.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.user_follower is not None:
            oprot.writeFieldBegin('user_follower', TType.LIST, 12)
            oprot.writeListBegin(TType.STRUCT, len(self.user_follower))
            for iter84 in self.user_follower:
                iter84.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.user_music is not None:
            oprot.writeFieldBegin('user_music', TType.LIST, 13)
            oprot.writeListBegin(TType.STRUCT, len(self.user_music))
            for iter85 in self.user_music:
                iter85.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.user_skill is not None:
            oprot.writeFieldBegin('user_skill', TType.LIST, 14)
            oprot.writeListBegin(TType.STRUCT, len(self.user_skill))
            for iter86 in self.user_skill:
                iter86.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.user_messenger is not None:
            oprot.writeFieldBegin('user_messenger', TType.LIST, 15)
            oprot.writeListBegin(TType.STRUCT, len(self.user_messenger))
            for iter87 in self.user_messenger:
                iter87.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.user_guitar is not None:
            oprot.writeFieldBegin('user_guitar', TType.LIST, 16)
            oprot.writeListBegin(TType.STRUCT, len(self.user_guitar))
            for iter88 in self.user_guitar:
                iter88.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.user_event_point is not None:
            oprot.writeFieldBegin('user_event_point', TType.LIST, 17)
            oprot.writeListBegin(TType.STRUCT, len(self.user_event_point))
            for iter89 in self.user_event_point:
                iter89.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.user_follower_quest is not None:
            oprot.writeFieldBegin('user_follower_quest', TType.LIST, 18)
            oprot.writeListBegin(TType.STRUCT, len(self.user_follower_quest))
            for iter90 in self.user_follower_quest:
                iter90.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class userSave(object):
    """
    Attributes:
     - call
     - data
     - common_data

    """
    thrift_spec = None


    def __init__(self, call = None, data = None, common_data = None,):
        self.call = call
        self.data = data
        self.common_data = common_data

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.call = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.data = userSaveDataInfo()
                    self.data.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRUCT:
                    self.common_data = tapsonic.general.ttypes.paramData()
                    self.common_data.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('userSave')
        if self.call is not None:
            oprot.writeFieldBegin('call', TType.STRING, 1)
            oprot.writeString(self.call.encode('utf-8') if sys.version_info[0] == 2 else self.call)
            oprot.writeFieldEnd()
        if self.data is not None:
            oprot.writeFieldBegin('data', TType.STRUCT, 2)
            self.data.write(oprot)
            oprot.writeFieldEnd()
        if self.common_data is not None:
            oprot.writeFieldBegin('common_data', TType.STRUCT, 3)
            self.common_data.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class userSaveRetDataInfo(object):
    """
    Attributes:
     - status

    """
    thrift_spec = None


    def __init__(self, status = None,):
        self.status = status

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.status = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('userSaveRetDataInfo')
        if self.status is not None:
            oprot.writeFieldBegin('status', TType.STRING, 1)
            oprot.writeString(self.status.encode('utf-8') if sys.version_info[0] == 2 else self.status)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class userSaveReturn(object):
    """
    Attributes:
     - error
     - server_time
     - mode
     - call
     - data
     - maintenance

    """
    thrift_spec = None


    def __init__(self, error = None, server_time = None, mode = None, call = None, data = None, maintenance = None,):
        self.error = error
        self.server_time = server_time
        self.mode = mode
        self.call = call
        self.data = data
        self.maintenance = maintenance

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.error = tapsonic.general.ttypes.errorRetCode()
                    self.error.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.server_time = tapsonic.general.ttypes.serverTimeRet()
                    self.server_time.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.mode = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRING:
                    self.call = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.STRUCT:
                    self.data = userSaveRetDataInfo()
                    self.data.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.STRUCT:
                    self.maintenance = tapsonic.general.ttypes.maintenanceData()
                    self.maintenance.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('userSaveReturn')
        if self.error is not None:
            oprot.writeFieldBegin('error', TType.STRUCT, 1)
            self.error.write(oprot)
            oprot.writeFieldEnd()
        if self.server_time is not None:
            oprot.writeFieldBegin('server_time', TType.STRUCT, 2)
            self.server_time.write(oprot)
            oprot.writeFieldEnd()
        if self.mode is not None:
            oprot.writeFieldBegin('mode', TType.STRING, 3)
            oprot.writeString(self.mode.encode('utf-8') if sys.version_info[0] == 2 else self.mode)
            oprot.writeFieldEnd()
        if self.call is not None:
            oprot.writeFieldBegin('call', TType.STRING, 4)
            oprot.writeString(self.call.encode('utf-8') if sys.version_info[0] == 2 else self.call)
            oprot.writeFieldEnd()
        if self.data is not None:
            oprot.writeFieldBegin('data', TType.STRUCT, 5)
            self.data.write(oprot)
            oprot.writeFieldEnd()
        if self.maintenance is not None:
            oprot.writeFieldBegin('maintenance', TType.STRUCT, 6)
            self.maintenance.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(saveUserInfo)
saveUserInfo.thrift_spec = (
    None,  # 0
    (1, TType.DOUBLE, 'u_like', None, None, ),  # 1
    (2, TType.I64, 'u_fans', None, None, ),  # 2
    (3, TType.I16, 'u_fans_grade', None, None, ),  # 3
    (4, TType.I64, 'u_selected_costume_id', None, None, ),  # 4
    (5, TType.I64, 'u_selected_music_id', None, None, ),  # 5
)
all_structs.append(saveUserAreaInfo)
saveUserAreaInfo.thrift_spec = (
    None,  # 0
    (1, TType.I16, 'u_area_num', None, None, ),  # 1
    (2, TType.DOUBLE, 'd_Like', None, None, ),  # 2
    (3, TType.I64, 'i_UserFanCount', None, None, ),  # 3
    (4, TType.I16, 'i_UserFanGrade', None, None, ),  # 4
    (5, TType.I64, 'i_SelectedCostumeId', None, None, ),  # 5
    (6, TType.I64, 'i_SelectedMusicId', None, None, ),  # 6
    (7, TType.I64, 'i_SelectedGuitarId', None, None, ),  # 7
    (8, TType.DOUBLE, 'd_Candy', None, None, ),  # 8
    (9, TType.STRING, 's_TutorialList', 'UTF8', None, ),  # 9
    (10, TType.STRING, 's_Gp1', 'UTF8', None, ),  # 10
    (11, TType.STRING, 's_Gp2', 'UTF8', None, ),  # 11
)
all_structs.append(saveUserAchievement)
saveUserAchievement.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'i_id', None, None, ),  # 1
    (2, TType.DOUBLE, 'd_Quantity', None, None, ),  # 2
    (3, TType.STRING, 's_Quantity', 'UTF8', None, ),  # 3
)
all_structs.append(saveUserCharacter)
saveUserCharacter.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'i_id', None, None, ),  # 1
    (2, TType.I64, 'i_Level', None, None, ),  # 2
    (3, TType.I64, 'i_BonusLevel', None, None, ),  # 3
)
all_structs.append(saveUserCostume)
saveUserCostume.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'i_id', None, None, ),  # 1
    (2, TType.I64, 'i_Level', None, None, ),  # 2
    (3, TType.I64, 'i_BonusLevel', None, None, ),  # 3
)
all_structs.append(saveUserDailyMission)
saveUserDailyMission.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'i_id', None, None, ),  # 1
    (2, TType.I64, 'd_Quantity', None, None, ),  # 2
)
all_structs.append(saveUserFollower)
saveUserFollower.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'i_id', None, None, ),  # 1
    (2, TType.I64, 'i_Level', None, None, ),  # 2
    (3, TType.I64, 'i_BonusLevel', None, None, ),  # 3
)
all_structs.append(saveUserMusic)
saveUserMusic.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'i_id', None, None, ),  # 1
    (2, TType.I64, 'i_Level', None, None, ),  # 2
    (3, TType.I64, 'i_BonusLevel', None, None, ),  # 3
    (4, TType.I64, 'b_EncoreBonusAppear', None, None, ),  # 4
    (5, TType.I64, 'i_EncoreBonusFollowerId', None, None, ),  # 5
)
all_structs.append(saveUserSkill)
saveUserSkill.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'i_id', None, None, ),  # 1
    (2, TType.I16, 'b_Activate', None, None, ),  # 2
    (3, TType.I64, 'l_ActivateOnTicks', None, None, ),  # 3
    (4, TType.I64, 'l_ActivateOffTicks', None, None, ),  # 4
)
all_structs.append(saveUserMessenger)
saveUserMessenger.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'i_MessengerChatRoomId', None, None, ),  # 1
    (2, TType.I64, 'i_LastConfirmIndex', None, None, ),  # 2
    (3, TType.STRING, 's_UnlockGroupList', 'UTF8', None, ),  # 3
    (4, TType.I64, 'l_UpdateTimeTicks', None, None, ),  # 4
)
all_structs.append(saveUserGuitar)
saveUserGuitar.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'i_id', None, None, ),  # 1
    (2, TType.I64, 'i_Level', None, None, ),  # 2
    (3, TType.I64, 'i_BonusLevel', None, None, ),  # 3
)
all_structs.append(saveUserEventPoint)
saveUserEventPoint.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 's_EventType', 'UTF8', None, ),  # 1
    (2, TType.I64, 'i_DataID', None, None, ),  # 2
    (3, TType.I64, 'i_Point', None, None, ),  # 3
    (4, TType.I64, 'i_Step', None, None, ),  # 4
    (5, TType.I32, 'i_Version', None, None, ),  # 5
)
all_structs.append(saveUserFollowerQuest)
saveUserFollowerQuest.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'i_CurrentID', None, None, ),  # 1
    (2, TType.DOUBLE, 'd_ConditionValue1', None, None, ),  # 2
    (3, TType.DOUBLE, 'd_ConditionValue2', None, None, ),  # 3
    (4, TType.DOUBLE, 'd_ConditionValue3', None, None, ),  # 4
)
all_structs.append(userSaveDataInfo)
userSaveDataInfo.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'u_seq', None, None, ),  # 1
    (2, TType.STRING, 'u_id', 'UTF8', None, ),  # 2
    (3, TType.STRING, 'uuid', 'UTF8', None, ),  # 3
    (4, TType.STRING, 'device_uuid', 'UTF8', None, ),  # 4
    (5, TType.STRING, 'type', 'UTF8', None, ),  # 5
    (6, TType.LIST, 'user_info', (TType.STRUCT, [saveUserInfo, None], False), None, ),  # 6
    (7, TType.LIST, 'user_area_info', (TType.STRUCT, [saveUserAreaInfo, None], False), None, ),  # 7
    (8, TType.LIST, 'user_achievement', (TType.STRUCT, [saveUserAchievement, None], False), None, ),  # 8
    (9, TType.LIST, 'user_character', (TType.STRUCT, [saveUserCharacter, None], False), None, ),  # 9
    (10, TType.LIST, 'user_costume', (TType.STRUCT, [saveUserCostume, None], False), None, ),  # 10
    (11, TType.LIST, 'user_daily_mission', (TType.STRUCT, [saveUserDailyMission, None], False), None, ),  # 11
    (12, TType.LIST, 'user_follower', (TType.STRUCT, [saveUserFollower, None], False), None, ),  # 12
    (13, TType.LIST, 'user_music', (TType.STRUCT, [saveUserMusic, None], False), None, ),  # 13
    (14, TType.LIST, 'user_skill', (TType.STRUCT, [saveUserSkill, None], False), None, ),  # 14
    (15, TType.LIST, 'user_messenger', (TType.STRUCT, [saveUserMessenger, None], False), None, ),  # 15
    (16, TType.LIST, 'user_guitar', (TType.STRUCT, [saveUserGuitar, None], False), None, ),  # 16
    (17, TType.LIST, 'user_event_point', (TType.STRUCT, [saveUserEventPoint, None], False), None, ),  # 17
    (18, TType.LIST, 'user_follower_quest', (TType.STRUCT, [saveUserFollowerQuest, None], False), None, ),  # 18
)
all_structs.append(userSave)
userSave.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'call', 'UTF8', None, ),  # 1
    (2, TType.STRUCT, 'data', [userSaveDataInfo, None], None, ),  # 2
    (3, TType.STRUCT, 'common_data', [tapsonic.general.ttypes.paramData, None], None, ),  # 3
)
all_structs.append(userSaveRetDataInfo)
userSaveRetDataInfo.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'status', 'UTF8', None, ),  # 1
)
all_structs.append(userSaveReturn)
userSaveReturn.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'error', [tapsonic.general.ttypes.errorRetCode, None], None, ),  # 1
    (2, TType.STRUCT, 'server_time', [tapsonic.general.ttypes.serverTimeRet, None], None, ),  # 2
    (3, TType.STRING, 'mode', 'UTF8', None, ),  # 3
    (4, TType.STRING, 'call', 'UTF8', None, ),  # 4
    (5, TType.STRUCT, 'data', [userSaveRetDataInfo, None], None, ),  # 5
    (6, TType.STRUCT, 'maintenance', [tapsonic.general.ttypes.maintenanceData, None], None, ),  # 6
)
fix_spec(all_structs)
del all_structs
