#
# Autogenerated by Thrift Compiler (0.22.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec
from uuid import UUID

import sys
import tapsonic.general.ttypes

from thrift.transport import TTransport
all_structs = []


class buyShopDataInfo(object):
    """
    Attributes:
     - u_seq
     - u_id
     - uuid
     - device_uuid
     - idx
     - developer_payload
     - pay_id
     - purchase_token
     - purchase_id
     - os
     - app_id
     - member_id

    """
    thrift_spec = None


    def __init__(self, u_seq = None, u_id = None, uuid = None, device_uuid = None, idx = None, developer_payload = None, pay_id = None, purchase_token = None, purchase_id = None, os = None, app_id = None, member_id = None,):
        self.u_seq = u_seq
        self.u_id = u_id
        self.uuid = uuid
        self.device_uuid = device_uuid
        self.idx = idx
        self.developer_payload = developer_payload
        self.pay_id = pay_id
        self.purchase_token = purchase_token
        self.purchase_id = purchase_id
        self.os = os
        self.app_id = app_id
        self.member_id = member_id

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.u_seq = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRING:
                    self.u_id = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.uuid = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRING:
                    self.device_uuid = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.I32:
                    self.idx = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.STRING:
                    self.developer_payload = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 7:
                if ftype == TType.STRING:
                    self.pay_id = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 8:
                if ftype == TType.STRING:
                    self.purchase_token = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 9:
                if ftype == TType.STRING:
                    self.purchase_id = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 10:
                if ftype == TType.I16:
                    self.os = iprot.readI16()
                else:
                    iprot.skip(ftype)
            elif fid == 11:
                if ftype == TType.STRING:
                    self.app_id = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 12:
                if ftype == TType.STRING:
                    self.member_id = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('buyShopDataInfo')
        if self.u_seq is not None:
            oprot.writeFieldBegin('u_seq', TType.I32, 1)
            oprot.writeI32(self.u_seq)
            oprot.writeFieldEnd()
        if self.u_id is not None:
            oprot.writeFieldBegin('u_id', TType.STRING, 2)
            oprot.writeString(self.u_id.encode('utf-8') if sys.version_info[0] == 2 else self.u_id)
            oprot.writeFieldEnd()
        if self.uuid is not None:
            oprot.writeFieldBegin('uuid', TType.STRING, 3)
            oprot.writeString(self.uuid.encode('utf-8') if sys.version_info[0] == 2 else self.uuid)
            oprot.writeFieldEnd()
        if self.device_uuid is not None:
            oprot.writeFieldBegin('device_uuid', TType.STRING, 4)
            oprot.writeString(self.device_uuid.encode('utf-8') if sys.version_info[0] == 2 else self.device_uuid)
            oprot.writeFieldEnd()
        if self.idx is not None:
            oprot.writeFieldBegin('idx', TType.I32, 5)
            oprot.writeI32(self.idx)
            oprot.writeFieldEnd()
        if self.developer_payload is not None:
            oprot.writeFieldBegin('developer_payload', TType.STRING, 6)
            oprot.writeString(self.developer_payload.encode('utf-8') if sys.version_info[0] == 2 else self.developer_payload)
            oprot.writeFieldEnd()
        if self.pay_id is not None:
            oprot.writeFieldBegin('pay_id', TType.STRING, 7)
            oprot.writeString(self.pay_id.encode('utf-8') if sys.version_info[0] == 2 else self.pay_id)
            oprot.writeFieldEnd()
        if self.purchase_token is not None:
            oprot.writeFieldBegin('purchase_token', TType.STRING, 8)
            oprot.writeString(self.purchase_token.encode('utf-8') if sys.version_info[0] == 2 else self.purchase_token)
            oprot.writeFieldEnd()
        if self.purchase_id is not None:
            oprot.writeFieldBegin('purchase_id', TType.STRING, 9)
            oprot.writeString(self.purchase_id.encode('utf-8') if sys.version_info[0] == 2 else self.purchase_id)
            oprot.writeFieldEnd()
        if self.os is not None:
            oprot.writeFieldBegin('os', TType.I16, 10)
            oprot.writeI16(self.os)
            oprot.writeFieldEnd()
        if self.app_id is not None:
            oprot.writeFieldBegin('app_id', TType.STRING, 11)
            oprot.writeString(self.app_id.encode('utf-8') if sys.version_info[0] == 2 else self.app_id)
            oprot.writeFieldEnd()
        if self.member_id is not None:
            oprot.writeFieldBegin('member_id', TType.STRING, 12)
            oprot.writeString(self.member_id.encode('utf-8') if sys.version_info[0] == 2 else self.member_id)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class buyShop(object):
    """
    Attributes:
     - call
     - data
     - sub_mode
     - common_data

    """
    thrift_spec = None


    def __init__(self, call = None, data = None, sub_mode = None, common_data = None,):
        self.call = call
        self.data = data
        self.sub_mode = sub_mode
        self.common_data = common_data

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.call = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.data = buyShopDataInfo()
                    self.data.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.sub_mode = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRUCT:
                    self.common_data = tapsonic.general.ttypes.paramData()
                    self.common_data.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('buyShop')
        if self.call is not None:
            oprot.writeFieldBegin('call', TType.STRING, 1)
            oprot.writeString(self.call.encode('utf-8') if sys.version_info[0] == 2 else self.call)
            oprot.writeFieldEnd()
        if self.data is not None:
            oprot.writeFieldBegin('data', TType.STRUCT, 2)
            self.data.write(oprot)
            oprot.writeFieldEnd()
        if self.sub_mode is not None:
            oprot.writeFieldBegin('sub_mode', TType.STRING, 3)
            oprot.writeString(self.sub_mode.encode('utf-8') if sys.version_info[0] == 2 else self.sub_mode)
            oprot.writeFieldEnd()
        if self.common_data is not None:
            oprot.writeFieldBegin('common_data', TType.STRUCT, 4)
            self.common_data.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class buyShopRetDataInfo(object):
    """
    Attributes:
     - u_cp
     - u_candy
     - reward_data
     - user_ad_level

    """
    thrift_spec = None


    def __init__(self, u_cp = None, u_candy = None, reward_data = None, user_ad_level = None,):
        self.u_cp = u_cp
        self.u_candy = u_candy
        self.reward_data = reward_data
        self.user_ad_level = user_ad_level

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.u_cp = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.DOUBLE:
                    self.u_candy = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.LIST:
                    self.reward_data = []
                    (_etype3, _size0) = iprot.readListBegin()
                    for _i4 in range(_size0):
                        _elem5 = tapsonic.general.ttypes.retReward()
                        _elem5.read(iprot)
                        self.reward_data.append(_elem5)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRUCT:
                    self.user_ad_level = tapsonic.general.ttypes.UserAdLevel()
                    self.user_ad_level.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('buyShopRetDataInfo')
        if self.u_cp is not None:
            oprot.writeFieldBegin('u_cp', TType.I64, 1)
            oprot.writeI64(self.u_cp)
            oprot.writeFieldEnd()
        if self.u_candy is not None:
            oprot.writeFieldBegin('u_candy', TType.DOUBLE, 2)
            oprot.writeDouble(self.u_candy)
            oprot.writeFieldEnd()
        if self.reward_data is not None:
            oprot.writeFieldBegin('reward_data', TType.LIST, 3)
            oprot.writeListBegin(TType.STRUCT, len(self.reward_data))
            for iter6 in self.reward_data:
                iter6.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.user_ad_level is not None:
            oprot.writeFieldBegin('user_ad_level', TType.STRUCT, 4)
            self.user_ad_level.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class buyShopReturn(object):
    """
    Attributes:
     - error
     - server_time
     - mode
     - call
     - data
     - maintenance

    """
    thrift_spec = None


    def __init__(self, error = None, server_time = None, mode = None, call = None, data = None, maintenance = None,):
        self.error = error
        self.server_time = server_time
        self.mode = mode
        self.call = call
        self.data = data
        self.maintenance = maintenance

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRUCT:
                    self.error = tapsonic.general.ttypes.errorRetCode()
                    self.error.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.server_time = tapsonic.general.ttypes.serverTimeRet()
                    self.server_time.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.mode = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRING:
                    self.call = iprot.readString().decode('utf-8', errors='replace') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.STRUCT:
                    self.data = buyShopRetDataInfo()
                    self.data.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.STRUCT:
                    self.maintenance = tapsonic.general.ttypes.maintenanceData()
                    self.maintenance.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        self.validate()
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('buyShopReturn')
        if self.error is not None:
            oprot.writeFieldBegin('error', TType.STRUCT, 1)
            self.error.write(oprot)
            oprot.writeFieldEnd()
        if self.server_time is not None:
            oprot.writeFieldBegin('server_time', TType.STRUCT, 2)
            self.server_time.write(oprot)
            oprot.writeFieldEnd()
        if self.mode is not None:
            oprot.writeFieldBegin('mode', TType.STRING, 3)
            oprot.writeString(self.mode.encode('utf-8') if sys.version_info[0] == 2 else self.mode)
            oprot.writeFieldEnd()
        if self.call is not None:
            oprot.writeFieldBegin('call', TType.STRING, 4)
            oprot.writeString(self.call.encode('utf-8') if sys.version_info[0] == 2 else self.call)
            oprot.writeFieldEnd()
        if self.data is not None:
            oprot.writeFieldBegin('data', TType.STRUCT, 5)
            self.data.write(oprot)
            oprot.writeFieldEnd()
        if self.maintenance is not None:
            oprot.writeFieldBegin('maintenance', TType.STRUCT, 6)
            self.maintenance.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(buyShopDataInfo)
buyShopDataInfo.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'u_seq', None, None, ),  # 1
    (2, TType.STRING, 'u_id', 'UTF8', None, ),  # 2
    (3, TType.STRING, 'uuid', 'UTF8', None, ),  # 3
    (4, TType.STRING, 'device_uuid', 'UTF8', None, ),  # 4
    (5, TType.I32, 'idx', None, None, ),  # 5
    (6, TType.STRING, 'developer_payload', 'UTF8', None, ),  # 6
    (7, TType.STRING, 'pay_id', 'UTF8', None, ),  # 7
    (8, TType.STRING, 'purchase_token', 'UTF8', None, ),  # 8
    (9, TType.STRING, 'purchase_id', 'UTF8', None, ),  # 9
    (10, TType.I16, 'os', None, None, ),  # 10
    (11, TType.STRING, 'app_id', 'UTF8', None, ),  # 11
    (12, TType.STRING, 'member_id', 'UTF8', None, ),  # 12
)
all_structs.append(buyShop)
buyShop.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'call', 'UTF8', None, ),  # 1
    (2, TType.STRUCT, 'data', [buyShopDataInfo, None], None, ),  # 2
    (3, TType.STRING, 'sub_mode', 'UTF8', None, ),  # 3
    (4, TType.STRUCT, 'common_data', [tapsonic.general.ttypes.paramData, None], None, ),  # 4
)
all_structs.append(buyShopRetDataInfo)
buyShopRetDataInfo.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'u_cp', None, None, ),  # 1
    (2, TType.DOUBLE, 'u_candy', None, None, ),  # 2
    (3, TType.LIST, 'reward_data', (TType.STRUCT, [tapsonic.general.ttypes.retReward, None], False), None, ),  # 3
    (4, TType.STRUCT, 'user_ad_level', [tapsonic.general.ttypes.UserAdLevel, None], None, ),  # 4
)
all_structs.append(buyShopReturn)
buyShopReturn.thrift_spec = (
    None,  # 0
    (1, TType.STRUCT, 'error', [tapsonic.general.ttypes.errorRetCode, None], None, ),  # 1
    (2, TType.STRUCT, 'server_time', [tapsonic.general.ttypes.serverTimeRet, None], None, ),  # 2
    (3, TType.STRING, 'mode', 'UTF8', None, ),  # 3
    (4, TType.STRING, 'call', 'UTF8', None, ),  # 4
    (5, TType.STRUCT, 'data', [buyShopRetDataInfo, None], None, ),  # 5
    (6, TType.STRUCT, 'maintenance', [tapsonic.general.ttypes.maintenanceData, None], None, ),  # 6
)
fix_spec(all_structs)
del all_structs
